;; catalog_current_test.clj — anti-rot gate for the GENERATED beagle fram-API catalog.
;;
;; The catalog (beagle/.../stdlib-fram.rkt) is generated by `bb bin/fram-primer
;; --beagle-catalog` from fram's own source. It is checked into beagle as a build
;; artifact. This gate fails if the committed file DRIFTS from the generator — i.e. if a
;; fram signature changed and the catalog wasn't regenerated. That keeps ONE source of
;; truth (fram's .bclj signatures); the catalog can never silently go stale by hand.
;;   BEAGLE=/path/to/beagle bb -cp out catalog_current_test.clj
(require '[clojure.java.io :as io] '[clojure.java.shell :as sh] '[clojure.string :as str])

(def beagle (or (System/getenv "BEAGLE") (str (System/getProperty "user.home") "/code/beagle")))
(def committed (str beagle "/beagle-lib/private/stdlib-fram.rkt"))

(when-not (.exists (io/file committed))
  (println "catalog_current_test: SKIP — beagle not present at" beagle "(set BEAGLE to enable)")
  (System/exit 0))

(def generated (:out (sh/sh "bb" "bin/fram-primer" "--beagle-catalog")))
(def have (slurp committed))

(if (= (str/trim generated) (str/trim have))
  (do (println "catalog_current_test: PASS — stdlib-fram.rkt is current with fram source"
               (str "(" (count (re-seq #"fram\.[a-z]+/" have)) " entries)"))
      (System/exit 0))
  (do (println "catalog_current_test: FAIL — beagle stdlib-fram.rkt DRIFTED from fram's source.")
      (println "  A fram signature changed without regenerating the catalog. Fix:")
      (println "    cd ~/code/fram && bb bin/fram-primer --beagle-catalog > \\")
      (println "      " committed)
      (System/exit 1)))
