;; FRI2 public facade; the implementation is generated from src/fri_port.bclj.
(ns fri
  (:require [fri-port :as fp]))

(def MAGIC fp/MAGIC)
(def FMT fp/FMT)
(def source-binding fp/source-binding)
(def write-fri! fp/write-fri!)
(def open-fri! fp/open-fri!)
(def close-fri! fp/close-fri!)
(def restore-store! fp/restore-store!)
(def space-id fp/space-id)
(def source-fingerprint fp/source-fingerprint)
(def source-position fp/source-position)
(def transaction-count fp/transaction-count)
(def operation-count fp/operation-count)
(def semantic-history fp/semantic-history)
(def operation-occurrences fp/operation-occurrences)
(def live-occurrences fp/live-occurrences)
(def live-propositions fp/live-propositions)
(def by-slot0 fp/by-slot0)
(def by-slot1 fp/by-slot1)
(def by-slot2 fp/by-slot2)
(def by-slot01 fp/by-slot01)
(def by-slot12 fp/by-slot12)
(def by-slot02 fp/by-slot02)
(def live-occurrences-as-of fp/live-occurrences-as-of)
(def live-propositions-as-of fp/live-propositions-as-of)
