;; FRI2 public facade; the implementation is generated from src/fri_port.bclj.
(ns fri
  (:require [fri-port :as fp]))

(def MAGIC fp/MAGIC)
(def FMT fp/FMT)
(def source-binding fp/source-binding)
(def write-fri! fp/write-fri!)
(def open-fri! fp/open-fri!)
(def close-fri! fp/close-fri!)
(def restore-store! fp/restore-store!)
(def space-id fp/space-id)
(def source-fingerprint fp/source-fingerprint)
(def source-position fp/source-position)
(def transaction-count fp/transaction-count)
(def operation-count fp/operation-count)
(def occurrences fp/occurrences)
(def withdrawals fp/withdrawals)
(def live-occurrences fp/live-occurrences)
(def live-propositions fp/live-propositions)
(def by-t1 fp/by-t1)
(def by-t2 fp/by-t2)
(def by-t3 fp/by-t3)
(def by-t12 fp/by-t12)
(def by-t23 fp/by-t23)
(def by-t13 fp/by-t13)
(def live-occurrences-as-of fp/live-occurrences-as-of)
(def live-propositions-as-of fp/live-propositions-as-of)
