// SPDX-License-Identifier: MIT OR Apache-2.0
#define _POSIX_C_SOURCE 200809L

#include "server_host.h"
#include "server_symbols.h"

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#define FRAM_SERVER_ADAPTER_ABI 4u
#define FRAM_SERVER_DEFAULT_ARENA_GROWTH_BYTES ((size_t)(64u * 1024u))
#define FRAM_SERVER_DEFAULT_COMPACT_GENERATIONS ((size_t)256u)
#define FRAM_SERVER_DEFAULT_COMPACT_INCREMENT_BYTES                    \
  ((size_t)(64u * 1024u * 1024u))
#define FRAM_SERVER_MIN_ARENA_GROWTH_BYTES ((size_t)(16u * 1024u))
#define FRAM_SERVER_MAX_ARENA_GROWTH_BYTES ((size_t)(8u * 1024u * 1024u))
#define FRAM_SERVER_MIN_COMPACT_GENERATIONS ((size_t)8u)
#define FRAM_SERVER_MIN_COMPACT_INCREMENT_BYTES                        \
  ((size_t)(1u * 1024u * 1024u))
#define FRAM_SERVER_BUDGET_ARENA_DIVISOR ((uint64_t)1024u)
#define FRAM_SERVER_BUDGET_COMPACT_DIVISOR ((uint64_t)4u)
#define FRAM_SERVER_BUDGET_GENERATION_BYTES ((uint64_t)(1u * 1024u * 1024u))
#define FRAM_SERVER_CAPABILITY_TOKEN UINT64_C(1)
#define FRAM_SERVER_FRAME_HEADER_BYTES ((size_t)26u)
#define FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET ((size_t)14u)
#define FRAM_SERVER_FRAME_MAX_BODY_BYTES UINT32_C(1048576)
#define FRAM_SERVER_FRAME_MAX_BYTES ((size_t)1048602u)
#define FRAM_SERVER_IO_CHUNK_BYTES ((size_t)8192u)

_Static_assert(FRAM_SERVER_ADAPTER_ABI ==
                   FRAM_SERVER_GENERATED_ABI,
               "server adapter ABI version");
_Static_assert(INT_MAX >= INT32_MAX, "generated status fits host int");
_Static_assert(sizeof(((native_capability *)0)->token) == sizeof(uint64_t),
               "native capability token ABI");
_Static_assert(sizeof(fram_server_generated_abi_return) == sizeof(int64_t),
               "generated ABI result width");
_Static_assert(sizeof(fram_server_store_boot_arg_0) == sizeof(uint64_t),
               "generated log-path Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_1) == sizeof(uint64_t),
               "generated space-id Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_2) ==
                   sizeof(native_byte_source *),
               "generated log byte-source ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_3) ==
                   sizeof(native_byte_source *),
               "generated snapshot byte-source ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_5) ==
                   sizeof(uint64_t),
               "generated StoreResult snapshot-report ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_6) ==
        sizeof(native_vec *),
    "generated ResponseResult snapshot ABI");
_Static_assert(sizeof(fram_server_codec_read_request_arg_0) ==
                   sizeof(native_byte_source *),
               "generated request byte-source ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_0) ==
                   sizeof(int64_t),
               "generated StoreResult status ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_3) ==
                   sizeof(int64_t),
               "generated StoreResult valid-log ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_4) ==
                   sizeof(native_vec *),
               "generated StoreResult boot-append ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated ResponseResult status ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_3) ==
        sizeof(native_vec *),
    "generated ResponseResult append ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_4) ==
        sizeof(fram_server_store_boot_return),
    "generated ResponseResult next-store ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_5) ==
        sizeof(bool),
    "generated ResponseResult state-change ABI");
_Static_assert(sizeof(fram_server_store_dispatch_arg_2) == sizeof(int64_t),
               "generated dispatch clock ABI");
_Static_assert(
    sizeof(((fram_server_store_shutdown_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated shutdown Status ABI");
_Static_assert(
    sizeof(((fram_server_codec_read_request_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated RequestResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated BytesResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_1) ==
        sizeof(native_vec *),
    "generated BytesResult vector ABI");

typedef struct fram_server_limits {
  size_t arena_growth_bytes;
  size_t compact_generations;
  size_t compact_increment_bytes;
} fram_server_limits;

typedef struct generated_owner {
  _Atomic size_t references;
  native_arena arena;
  native_capability capability;
} generated_owner;

typedef struct generated_store_generation {
  _Atomic size_t references;
  generated_owner *owner;
  struct generated_store_generation *parent;
  fram_server_store_boot_return result;
  size_t chain_reserved_bytes;
  size_t chain_generations;
} generated_store_generation;

struct fram_server_store {
  generated_store_generation *current;
  char *canonical_log_path;
  char *space_id;
  fram_server_host_v1 host;
  fram_server_limits limits;
  bool poisoned;
  size_t compaction_base_bytes;
  size_t compaction_base_generations;
};

#ifndef FRAM_WASM_HOST_IMPORTS
typedef struct posix_storage {
  int fd;
} posix_storage;
#endif

struct fram_server_request {
  generated_owner *owner;
  fram_server_codec_read_request_return result;
};

/* The response frame is copied out of the generated module's arenas while
   dispatch still holds them live, so a response in flight references no store
   generation and no request arena: a slow or held client socket can never pin
   store memory. */
struct fram_server_response {
  uint8_t *bytes;
  size_t length;
};

static void clear_error(char *error, size_t error_capacity) {
  if (error != NULL && error_capacity != 0u) {
    error[0] = '\0';
  }
}

static void copy_error(char *error, size_t error_capacity,
                       const char *detail) {
  size_t length;
  size_t copied;

  if (error == NULL || error_capacity == 0u) {
    return;
  }
  length = strlen(detail);
  copied = length < error_capacity - 1u ? length : error_capacity - 1u;
  if (copied != 0u) {
    memcpy(error, detail, copied);
  }
  error[copied] = '\0';
}

static char *duplicate_string(const char *source, char *error,
                              size_t error_capacity) {
  size_t length = strlen(source);
  char *copy;

  if (length == SIZE_MAX) {
    copy_error(error, error_capacity, "generated string length overflowed");
    return NULL;
  }
  copy = malloc(length + 1u);
  if (copy == NULL) {
    copy_error(error, error_capacity, "cannot allocate generated host text");
    return NULL;
  }
  memcpy(copy, source, length + 1u);
  return copy;
}

/* A budget of zero means the host named none, and every default stands. */
static fram_server_limits derive_limits(uint64_t budget_bytes) {
  fram_server_limits limits;
  uint64_t growth;
  uint64_t increment;
  uint64_t generations;

  limits.arena_growth_bytes = FRAM_SERVER_DEFAULT_ARENA_GROWTH_BYTES;
  limits.compact_generations = FRAM_SERVER_DEFAULT_COMPACT_GENERATIONS;
  limits.compact_increment_bytes = FRAM_SERVER_DEFAULT_COMPACT_INCREMENT_BYTES;
  if (budget_bytes == UINT64_C(0)) {
    return limits;
  }
  if (budget_bytes > (uint64_t)SIZE_MAX) {
    budget_bytes = (uint64_t)SIZE_MAX;
  }
  growth = budget_bytes / FRAM_SERVER_BUDGET_ARENA_DIVISOR;
  if (growth < (uint64_t)FRAM_SERVER_MIN_ARENA_GROWTH_BYTES) {
    growth = (uint64_t)FRAM_SERVER_MIN_ARENA_GROWTH_BYTES;
  }
  if (growth > (uint64_t)FRAM_SERVER_MAX_ARENA_GROWTH_BYTES) {
    growth = (uint64_t)FRAM_SERVER_MAX_ARENA_GROWTH_BYTES;
  }
  increment = budget_bytes / FRAM_SERVER_BUDGET_COMPACT_DIVISOR;
  if (increment < (uint64_t)FRAM_SERVER_MIN_COMPACT_INCREMENT_BYTES) {
    increment = (uint64_t)FRAM_SERVER_MIN_COMPACT_INCREMENT_BYTES;
  }
  if (increment > (uint64_t)FRAM_SERVER_DEFAULT_COMPACT_INCREMENT_BYTES) {
    increment = (uint64_t)FRAM_SERVER_DEFAULT_COMPACT_INCREMENT_BYTES;
  }
  generations = budget_bytes / FRAM_SERVER_BUDGET_GENERATION_BYTES;
  if (generations < (uint64_t)FRAM_SERVER_MIN_COMPACT_GENERATIONS) {
    generations = (uint64_t)FRAM_SERVER_MIN_COMPACT_GENERATIONS;
  }
  if (generations > (uint64_t)FRAM_SERVER_DEFAULT_COMPACT_GENERATIONS) {
    generations = (uint64_t)FRAM_SERVER_DEFAULT_COMPACT_GENERATIONS;
  }
  limits.arena_growth_bytes = (size_t)growth;
  limits.compact_increment_bytes = (size_t)increment;
  limits.compact_generations = (size_t)generations;
  return limits;
}

static generated_owner *owner_create(size_t arena_growth_bytes, char *error,
                                     size_t error_capacity) {
  generated_owner *owner;

  owner = malloc(sizeof(*owner));
  if (owner == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated owner");
    return NULL;
  }
  if (!native_arena_init_growable(&owner->arena, arena_growth_bytes)) {
    free(owner);
    copy_error(error, error_capacity,
               "cannot allocate the generated Beagle arena");
    return NULL;
  }
  atomic_init(&owner->references, (size_t)1u);
  owner->capability.token = FRAM_SERVER_CAPABILITY_TOKEN;
  return owner;
}

static void owner_retain(generated_owner *owner) {
  (void)atomic_fetch_add_explicit(&owner->references, (size_t)1u,
                                  memory_order_relaxed);
}

static void owner_release(generated_owner *owner) {
  if (atomic_fetch_sub_explicit(&owner->references, (size_t)1u,
                                memory_order_acq_rel) == (size_t)1u) {
    native_arena_destroy(&owner->arena);
    free(owner);
  }
}

static generated_store_generation *generation_create(
    generated_owner *owner, generated_store_generation *parent,
    fram_server_store_boot_return result, char *error,
    size_t error_capacity) {
  generated_store_generation *generation = malloc(sizeof(*generation));
  size_t own_reserved;

  if (generation == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated store generation");
    return NULL;
  }
  own_reserved = native_arena_reserved_bytes(&owner->arena);
  if (parent != NULL &&
      parent->chain_reserved_bytes > SIZE_MAX - own_reserved) {
    free(generation);
    copy_error(error, error_capacity,
               "generated store generation accounting overflowed");
    return NULL;
  }
  atomic_init(&generation->references, (size_t)1u);
  owner_retain(owner);
  generation->owner = owner;
  generation->parent = parent;
  if (parent != NULL) {
    (void)atomic_fetch_add_explicit(&parent->references, (size_t)1u,
                                    memory_order_relaxed);
  }
  generation->result = result;
  generation->chain_reserved_bytes =
      own_reserved + (parent == NULL ? 0u : parent->chain_reserved_bytes);
  generation->chain_generations =
      (size_t)1u + (parent == NULL ? 0u : parent->chain_generations);
  return generation;
}

static void generation_release(generated_store_generation *generation) {
  generated_store_generation *parent;

  if (atomic_fetch_sub_explicit(&generation->references, (size_t)1u,
                                memory_order_acq_rel) != (size_t)1u) {
    return;
  }
  parent = generation->parent;
  owner_release(generation->owner);
  free(generation);
  if (parent != NULL) {
    generation_release(parent);
  }
}

static uint64_t native_text_from_c(native_arena *arena, const char *text) {
  size_t length = strlen(text);
  uint8_t *destination = NULL;
  uint64_t result = native_text_alloc(arena, (uint64_t)length, &destination);

  if (length != 0u) {
    memcpy(destination, text, length);
  }
  return result;
}

/* The generated module reads octets in place, so the bridge hands it a handle
   over the caller's buffer. The buffer must outlive the call. */
static bool borrow_bytes(native_arena *arena, const uint8_t *bytes,
                         size_t length, native_byte_source **source_out,
                         char *error, size_t error_capacity) {
  if (length > (size_t)INT64_MAX) {
    copy_error(error, error_capacity,
               "generated byte input exceeds the native address range");
    return false;
  }
  *source_out = native_byte_source_borrow(arena, bytes, (int64_t)length);
  return true;
}

static int generated_status(int64_t status, char *error,
                            size_t error_capacity,
                            const char *failure_detail) {
  if (status == (int64_t)FRAM_SERVER_OK) {
    return FRAM_SERVER_OK;
  }
  copy_error(error, error_capacity, failure_detail);
  return FRAM_SERVER_FATAL;
}

// The POSIX storage and realtime regime is the host of last resort; a build
// that names its own host imports compiles it out rather than linking it dead.
#ifndef FRAM_WASM_HOST_IMPORTS
static int posix_realtime_milliseconds(void *context,
                                       int64_t *milliseconds_out, char *error,
                                       size_t error_capacity) {
  struct timespec now;

  (void)context;

  if (clock_gettime(CLOCK_REALTIME, &now) != 0 || now.tv_sec < (time_t)0 ||
      now.tv_nsec < 0 || now.tv_nsec >= 1000000000L ||
      (uintmax_t)now.tv_sec > (uintmax_t)(INT64_MAX / INT64_C(1000))) {
    copy_error(error, error_capacity,
               "cannot read a bounded realtime dispatch clock");
    return FRAM_SERVER_FATAL;
  }
  *milliseconds_out =
      (int64_t)now.tv_sec * INT64_C(1000) + (int64_t)(now.tv_nsec / 1000000L);
  return FRAM_SERVER_OK;
}
#endif

/* snapshot_context is allowed to be NULL: a host may serve no snapshot object,
   and a checkpoint then reports that instead of writing one. */
static bool valid_host(const fram_server_host_v1 *host) {
  return host != NULL && host->abi_version == FRAM_SERVER_HOST_ABI &&
         host->struct_size >= (uint32_t)sizeof(*host) &&
         host->clock_milliseconds != NULL && host->storage_size != NULL &&
         host->storage_read != NULL && host->storage_truncate != NULL &&
         host->storage_append != NULL && host->storage_sync != NULL &&
         host->storage_close != NULL;
}

static int read_exact(int fd, uint8_t *destination, size_t length,
                      bool clean_eof_is_peer_closed,
                      int failure_status,
                      const char *truncated_detail, const char *read_detail,
                      char *error, size_t error_capacity) {
  size_t position = 0u;

  while (position < length) {
    ssize_t count = read(fd, destination + position, length - position);

    if (count > 0) {
      position += (size_t)count;
      continue;
    }
    if (count == 0) {
      if (position == 0u && clean_eof_is_peer_closed) {
        return FRAM_SERVER_PEER_CLOSED;
      }
      copy_error(error, error_capacity, truncated_detail);
      return failure_status;
    }
    if (errno == EINTR) {
      continue;
    }
    copy_error(error, error_capacity, read_detail);
    return failure_status;
  }
  return FRAM_SERVER_OK;
}

#ifndef FRAM_WASM_HOST_IMPORTS
static int posix_storage_open(const char *path, posix_storage **storage_out,
                              char *error, size_t error_capacity) {
  struct stat status;
  posix_storage *storage = malloc(sizeof(*storage));

  if (storage == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the POSIX FRAMLOG owner");
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  storage->fd = open(path, O_RDWR | O_CREAT | O_CLOEXEC, 0666);

  if (storage->fd < 0) {
    free(storage);
    copy_error(error, error_capacity, "cannot open the canonical FRAMLOG");
    return FRAM_SERVER_HOST_ERROR;
  }
  if (fstat(storage->fd, &status) != 0 || !S_ISREG(status.st_mode) ||
      status.st_size < 0) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is not a readable regular file");
    (void)close(storage->fd);
    free(storage);
    return FRAM_SERVER_HOST_ERROR;
  }
  // wasip1 links no flock, so on wasm sole writer authority is the embedder's
  // grant — the same obligation fram.h already places on a host storage table.
#ifndef __wasi__
  if (flock(storage->fd, LOCK_EX | LOCK_NB) != 0) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG writer authority is unavailable");
    (void)close(storage->fd);
    free(storage);
    return FRAM_SERVER_HOST_ERROR;
  }
#endif
  *storage_out = storage;
  return FRAM_SERVER_OK;
}

static int posix_storage_size(void *context, uint64_t *size_out, char *error,
                              size_t error_capacity) {
  posix_storage *storage = context;
  struct stat status;

  if (fstat(storage->fd, &status) != 0 || !S_ISREG(status.st_mode) ||
      status.st_size < 0) {
    copy_error(error, error_capacity,
               "cannot inspect the canonical FRAMLOG");
    return FRAM_SERVER_HOST_ERROR;
  }
  *size_out = (uint64_t)status.st_size;
  return FRAM_SERVER_OK;
}

static int posix_storage_read(void *context, uint64_t offset,
                              uint8_t *destination, size_t length, char *error,
                              size_t error_capacity) {
  posix_storage *storage = context;
  size_t position = 0u;

  if (offset > (uint64_t)INT64_MAX ||
      length > (size_t)(INT64_MAX - (int64_t)offset)) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG read exceeds the POSIX range");
    return FRAM_SERVER_HOST_ERROR;
  }
  while (position < length) {
    ssize_t count = pread(storage->fd, destination + position,
                          length - position,
                          (off_t)(offset + (uint64_t)position));

    if (count > 0) {
      position += (size_t)count;
    } else if (count < 0 && errno == EINTR) {
      continue;
    } else {
      copy_error(error, error_capacity,
                 count == 0 ? "canonical FRAMLOG ended while reading"
                            : "cannot read the canonical FRAMLOG");
      return FRAM_SERVER_HOST_ERROR;
    }
  }
  return FRAM_SERVER_OK;
}

static int posix_storage_truncate(void *context, uint64_t length, char *error,
                                  size_t error_capacity) {
  posix_storage *storage = context;
  off_t offset = (off_t)length;

  if ((uint64_t)offset != length || ftruncate(storage->fd, offset) != 0) {
    copy_error(error, error_capacity,
               "cannot repair the canonical FRAMLOG tail");
    return FRAM_SERVER_HOST_ERROR;
  }
  return FRAM_SERVER_OK;
}

static int posix_storage_append(void *context, const uint8_t *bytes,
                                size_t length, char *error,
                                size_t error_capacity) {
  posix_storage *storage = context;
  size_t position = 0u;

  // Parenthesized: wasi-libc defines lseek as a statement-expression macro,
  // which -pedantic rejects; the parentheses suppress that expansion.
  if ((lseek)(storage->fd, (off_t)0, SEEK_END) < (off_t)0) {
    copy_error(error, error_capacity, "cannot seek the canonical FRAMLOG");
    return FRAM_SERVER_HOST_ERROR;
  }
  while (position < length) {
    ssize_t count = write(storage->fd, bytes + position, length - position);

    if (count > 0) {
      position += (size_t)count;
    } else if (count < 0 && errno == EINTR) {
      continue;
    } else {
      copy_error(error, error_capacity,
                 "cannot append the canonical FRAMLOG");
      return FRAM_SERVER_HOST_ERROR;
    }
  }
  return FRAM_SERVER_OK;
}

static int posix_storage_sync(void *context, char *error,
                              size_t error_capacity) {
  posix_storage *storage = context;

  if (fsync(storage->fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    return FRAM_SERVER_HOST_ERROR;
  }
  return FRAM_SERVER_OK;
}

static int posix_storage_close(void *context, char *error,
                               size_t error_capacity) {
  posix_storage *storage = context;
  int status = FRAM_SERVER_OK;

  if (close(storage->fd) != 0) {
    copy_error(error, error_capacity, "cannot close the canonical FRAMLOG");
    status = FRAM_SERVER_HOST_ERROR;
  }
  free(storage);
  return status;
}
#endif

static int vector_length(const native_vec *vector, size_t minimum,
                         size_t maximum, size_t *length_out, char *error,
                         size_t error_capacity,
                         const char *invalid_detail) {
  int64_t length;

  if (vector == NULL) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  length = native_vec_length(vector);
  if (length < INT64_C(0) || (uint64_t)length > (uint64_t)SIZE_MAX ||
      (size_t)length < minimum || (size_t)length > maximum) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  *length_out = (size_t)length;
  return FRAM_SERVER_OK;
}

static int write_bytes(int fd, const uint8_t *bytes, size_t length,
                       char *error, size_t error_capacity) {
  size_t position = 0u;

  while (position < length) {
    ssize_t count = write(fd, bytes + position, length - position);

    if (count > 0) {
      position += (size_t)count;
    } else if (count < 0 && errno == EINTR) {
      continue;
    } else if (count < 0 && (errno == EPIPE || errno == ECONNRESET)) {
      return FRAM_SERVER_PEER_CLOSED;
    } else {
      copy_error(error, error_capacity,
                 "cannot write the generated response frame");
      return FRAM_SERVER_CLIENT_ERROR;
    }
  }
  return FRAM_SERVER_OK;
}

static int append_log_vector(fram_server_store *store,
                             const native_vec *vector, bool sync_after_write,
                             char *error, size_t error_capacity) {
  uint8_t chunk[FRAM_SERVER_IO_CHUNK_BYTES];
  size_t length;
  size_t offset = 0u;
  int status = vector_length(vector, 0u, SIZE_MAX, &length, error,
                             error_capacity,
                             "generated FRAMLOG append is not byte-valued");

  if (status != FRAM_SERVER_OK || length == 0u) {
    return status;
  }
  while (offset < length) {
    size_t count = length - offset;
    size_t index;

    if (count > sizeof(chunk)) {
      count = sizeof(chunk);
    }
    for (index = 0u; index < count; index += 1u) {
      const int64_t *value = native_vec_at(
          vector, (int64_t)(offset + index), INT64_C(8));

      if (*value < INT64_C(0) || *value > INT64_C(255)) {
        copy_error(error, error_capacity,
                   "generated FRAMLOG append is not byte-valued");
        return FRAM_SERVER_FATAL;
      }
      chunk[index] = (uint8_t)*value;
    }
    status = store->host.storage_append(store->host.context, chunk, count,
                                        error, error_capacity);
    if (status != FRAM_SERVER_OK) {
      return status;
    }
    offset += count;
  }
  if (sync_after_write) {
    status = store->host.storage_sync(store->host.context, error,
                                      error_capacity);
    if (status != FRAM_SERVER_OK) {
      return status;
    }
  }
  return FRAM_SERVER_OK;
}

static int repair_log_tail(fram_server_store *store,
                           size_t original_length, int64_t valid_length,
                           char *error, size_t error_capacity) {
  if (valid_length < INT64_C(0) ||
      (uint64_t)valid_length > (uint64_t)original_length) {
    copy_error(error, error_capacity,
               "generated FRAMLOG recovery returned an invalid prefix");
    return FRAM_SERVER_FATAL;
  }
  if ((size_t)valid_length == original_length) {
    return FRAM_SERVER_OK;
  }
  return store->host.storage_truncate(
      store->host.context, (uint64_t)valid_length, error, error_capacity);
}

static uint32_t frame_body_length(const uint8_t *header) {
  return (uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET] |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 1u]
          << 8u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 2u]
          << 16u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 3u]
          << 24u);
}

static int read_frame(int fd, uint8_t **frame_out, size_t *length_out,
                      char *error, size_t error_capacity) {
  uint8_t header[FRAM_SERVER_FRAME_HEADER_BYTES];
  uint8_t *frame;
  uint32_t body_length;
  size_t frame_length;
  int status = read_exact(
      fd, header, sizeof(header), true, FRAM_SERVER_CLIENT_ERROR,
      "generated request frame ended inside its header",
      "cannot read the generated request frame header", error,
      error_capacity);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  body_length = frame_body_length(header);
  if (body_length > FRAM_SERVER_FRAME_MAX_BODY_BYTES) {
    copy_error(error, error_capacity,
               "generated request frame exceeds the body limit");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  frame_length = sizeof(header) + (size_t)body_length;
  frame = malloc(frame_length);
  if (frame == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request frame");
    return FRAM_SERVER_FATAL;
  }
  memcpy(frame, header, sizeof(header));
  status = read_exact(fd, frame + sizeof(header), (size_t)body_length, false,
                      FRAM_SERVER_CLIENT_ERROR,
                      "generated request frame ended inside its body",
                      "cannot read the generated request frame body", error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    free(frame);
    return status;
  }
  *frame_out = frame;
  *length_out = frame_length;
  return FRAM_SERVER_OK;
}

static int read_whole_object(const fram_server_host_v1 *host, void *context,
                             uint8_t **bytes_out, size_t *length_out,
                             const char *oversize_detail,
                             const char *allocate_detail, char *error,
                             size_t error_capacity) {
  uint64_t host_length;
  size_t length;
  uint8_t *bytes = NULL;
  int status;

  *bytes_out = NULL;
  *length_out = 0u;
  status = host->storage_size(context, &host_length, error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  if (host_length > (uint64_t)SIZE_MAX || host_length > (uint64_t)INT64_MAX) {
    copy_error(error, error_capacity, oversize_detail);
    return FRAM_SERVER_FATAL;
  }
  length = (size_t)host_length;
  if (length != 0u) {
    bytes = malloc(length);
    if (bytes == NULL) {
      copy_error(error, error_capacity, allocate_detail);
      return FRAM_SERVER_OUT_OF_MEMORY;
    }
  }
  status = host->storage_read(context, UINT64_C(0), bytes, length, error,
                              error_capacity);
  if (status != FRAM_SERVER_OK) {
    free(bytes);
    return status;
  }
  *bytes_out = bytes;
  *length_out = length;
  return FRAM_SERVER_OK;
}

/* Silent in the host-import regime: that guest holds no stderr capability, so
   its embedder reads the route from the image object instead. */
static void report_snapshot_line(uint64_t text) {
#ifdef FRAM_WASM_HOST_IMPORTS
  (void)text;
#else
  uint64_t length = native_text_length(text);
  const uint8_t *bytes = native_text_bytes(text);

  if (length == UINT64_C(0) || bytes == NULL ||
      length > (uint64_t)FRAM_SERVER_ERROR_CAPACITY) {
    return;
  }
  (void)!write(2, bytes, (size_t)length);
  (void)!write(2, "\n", (size_t)1u);
#endif
}

/* Only a host that named a budget gets this line, so a default boot's stderr
   is byte-identical to what it was before limits became derivable. */
static void report_derived_limits(const fram_server_limits *limits) {
#ifdef FRAM_WASM_HOST_IMPORTS
  (void)limits;
#else
  char line[160];
  int length = snprintf(
      line, sizeof(line),
      "fram: engine memory limits derived from the host budget: "
      "arena-growth=%llu compact-increment=%llu compact-generations=%llu\n",
      (unsigned long long)limits->arena_growth_bytes,
      (unsigned long long)limits->compact_increment_bytes,
      (unsigned long long)limits->compact_generations);

  if (length > 0) {
    (void)!write(2, line,
                 (size_t)length < sizeof(line) ? (size_t)length
                                               : sizeof(line) - 1u);
  }
#endif
}

static int write_snapshot_vector(fram_server_store *store,
                                 const native_vec *vector, char *error,
                                 size_t error_capacity) {
  uint8_t chunk[FRAM_SERVER_IO_CHUNK_BYTES];
  size_t length;
  size_t offset = 0u;
  int status = vector_length(vector, 0u, SIZE_MAX, &length, error,
                             error_capacity,
                             "generated snapshot image is not byte-valued");

  if (status != FRAM_SERVER_OK || length == 0u) {
    return status;
  }
  if (store->host.snapshot_context == NULL) {
    copy_error(error, error_capacity,
               "this host serves no snapshot storage object");
    return FRAM_SERVER_HOST_ERROR;
  }
  status = store->host.storage_truncate(store->host.snapshot_context,
                                        UINT64_C(0), error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  while (offset < length) {
    size_t count = length - offset;
    size_t index;

    if (count > sizeof(chunk)) {
      count = sizeof(chunk);
    }
    for (index = 0u; index < count; index += 1u) {
      const int64_t *value = native_vec_at(
          vector, (int64_t)(offset + index), INT64_C(8));

      if (*value < INT64_C(0) || *value > INT64_C(255)) {
        copy_error(error, error_capacity,
                   "generated snapshot image is not byte-valued");
        return FRAM_SERVER_FATAL;
      }
      chunk[index] = (uint8_t)*value;
    }
    status = store->host.storage_append(store->host.snapshot_context, chunk,
                                        count, error, error_capacity);
    if (status != FRAM_SERVER_OK) {
      return status;
    }
    offset += count;
  }
  return store->host.storage_sync(store->host.snapshot_context, error,
                                  error_capacity);
}

static int boot_generation_from_log(
    fram_server_store *store, const char *canonical_log_path,
    const char *space_id, bool report_snapshot,
    generated_store_generation **generation_out, size_t *log_length_out,
    char *error, size_t error_capacity) {
  generated_owner *owner = NULL;
  generated_store_generation *generation = NULL;
  uint8_t *log_bytes = NULL;
  uint8_t *snapshot_bytes = NULL;
  native_byte_source *borrowed = NULL;
  native_byte_source *borrowed_snapshot = NULL;
  size_t log_length = 0u;
  size_t snapshot_length = 0u;
  fram_server_store_boot_arg_0 generated_log_path;
  fram_server_store_boot_arg_1 generated_space_id;
  fram_server_store_boot_return result;
  int status;

  *generation_out = NULL;
  status = read_whole_object(
      &store->host, store->host.context, &log_bytes, &log_length,
      "canonical FRAMLOG exceeds the native address range",
      "cannot allocate the canonical FRAMLOG input", error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  if (store->host.snapshot_context != NULL) {
    status = read_whole_object(
        &store->host, store->host.snapshot_context, &snapshot_bytes,
        &snapshot_length, "snapshot image exceeds the native address range",
        "cannot allocate the snapshot image input", error, error_capacity);
    if (status != FRAM_SERVER_OK) {
      free(log_bytes);
      return status;
    }
  }
  owner = owner_create(store->limits.arena_growth_bytes, error,
                       error_capacity);
  if (owner == NULL) {
    free(log_bytes);
    free(snapshot_bytes);
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  if (!borrow_bytes(&owner->arena, log_bytes, log_length, &borrowed, error,
                    error_capacity) ||
      !borrow_bytes(&owner->arena, snapshot_bytes, snapshot_length,
                    &borrowed_snapshot, error, error_capacity)) {
    status = FRAM_SERVER_FATAL;
    goto cleanup;
  }
  generated_log_path = native_text_from_c(&owner->arena, canonical_log_path);
  generated_space_id =
      native_text_from_c(&owner->arena, space_id != NULL ? space_id : "");
  result = FRAM_SERVER_CALL_STORE_BOOT(
      &owner->arena, &owner->capability, generated_log_path,
      generated_space_id, borrowed, borrowed_snapshot);
  status = generated_status((int64_t)result.field_0, error, error_capacity,
                            "generated store boot failed");
  if (status == FRAM_SERVER_OK) {
    if (report_snapshot) {
      report_snapshot_line(result.field_5);
    }
    generation = generation_create(owner, NULL, result, error, error_capacity);
    if (generation == NULL) {
      status = FRAM_SERVER_FATAL;
    }
  }

cleanup:
  free(log_bytes);
  free(snapshot_bytes);
  owner_release(owner);
  if (status != FRAM_SERVER_OK) {
    if (generation != NULL) {
      generation_release(generation);
    }
    return status;
  }
  *generation_out = generation;
  *log_length_out = log_length;
  return FRAM_SERVER_OK;
}

static bool store_needs_compaction(const fram_server_store *store) {
  const generated_store_generation *current = store->current;

  return current->chain_generations - store->compaction_base_generations >=
             store->limits.compact_generations ||
         current->chain_reserved_bytes - store->compaction_base_bytes >=
             store->limits.compact_increment_bytes;
}

static int compact_store(fram_server_store *store, char *error,
                         size_t error_capacity) {
  generated_store_generation *replacement = NULL;
  generated_store_generation *previous;
  size_t log_length;
  size_t append_length;
  int status = boot_generation_from_log(
      store, store->canonical_log_path, store->space_id, false, &replacement,
      &log_length, error, error_capacity);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  status = vector_length(replacement->result.field_4, 0u, SIZE_MAX,
                         &append_length, error, error_capacity,
                         "generated compacted FRAMLOG append is invalid");
  if (status != FRAM_SERVER_OK || append_length != 0u ||
      replacement->result.field_3 < INT64_C(0) ||
      (uint64_t)replacement->result.field_3 != (uint64_t)log_length) {
    generation_release(replacement);
    copy_error(error, error_capacity,
               "generated compaction did not consume the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  previous = store->current;
  store->current = replacement;
  store->compaction_base_bytes = replacement->chain_reserved_bytes;
  store->compaction_base_generations = replacement->chain_generations;
  generation_release(previous);
  return FRAM_SERVER_OK;
}

/* Compaction is what returns a generation chain's arenas to the allocator, and
   until now only a write could reach it: an idle server parked forever on
   whichever peak its last write left. The chain carries its own answer to
   "would this repeat work" -- a compacted store has exactly one generation and
   sets its base to it, so any excess over the base is unprojected writes. */
int fram_server_store_compact_idle(fram_server_store *store,
                                   int *compacted_out, char *error,
                                   size_t error_capacity) {
  int status;

  clear_error(error, error_capacity);
  if (compacted_out != NULL) {
    *compacted_out = 0;
  }
  if (store == NULL) {
    copy_error(error, error_capacity,
               "generated idle compaction requires an owned store");
    return FRAM_SERVER_FATAL;
  }
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    return FRAM_SERVER_FATAL;
  }
  if (store->current->chain_generations <=
      store->compaction_base_generations) {
    return FRAM_SERVER_OK;
  }
  status = compact_store(store, error, error_capacity);
  if (status == FRAM_SERVER_OK && compacted_out != NULL) {
    *compacted_out = 1;
  }
  return status;
}

uint32_t fram_server_generated_abi(void) {
  generated_owner *owner =
      owner_create(FRAM_SERVER_DEFAULT_ARENA_GROWTH_BYTES, NULL, 0u);
  fram_server_generated_abi_return result;

  if (owner == NULL) {
    return UINT32_C(0);
  }
  result = FRAM_SERVER_CALL_GENERATED_ABI(&owner->arena,
                                              &owner->capability);
  owner_release(owner);
  if ((int64_t)result < INT64_C(0) ||
      (int64_t)result > (int64_t)UINT32_MAX) {
    return UINT32_C(0);
  }
  return (uint32_t)result;
}

int fram_server_store_boot_with_host(const char *canonical_log_path,
                                     const char *space_id,
                                     const fram_server_host_v1 *host,
                                     fram_server_store **store_out,
                                     char *error, size_t error_capacity) {
  fram_server_store *store = NULL;
  generated_store_generation *generation = NULL;
  size_t log_length;
  size_t append_length;
  int status;

  clear_error(error, error_capacity);
  if (store_out == NULL || canonical_log_path == NULL || !valid_host(host)) {
    copy_error(error, error_capacity,
               "generated store boot requires a log label, host, and output owner");
    return FRAM_SERVER_FATAL;
  }
  *store_out = NULL;
  store = malloc(sizeof(*store));
  if (store == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated store wrapper");
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  memset(store, 0, sizeof(*store));
  store->canonical_log_path =
      duplicate_string(canonical_log_path, error, error_capacity);
  store->space_id = duplicate_string(space_id != NULL ? space_id : "", error,
                                     error_capacity);
  if (store->canonical_log_path == NULL || store->space_id == NULL) {
    status = FRAM_SERVER_OUT_OF_MEMORY;
    goto boot_failed;
  }
  store->host = *host;
  store->limits = derive_limits(host->memory_budget_bytes);
  store->poisoned = false;
  if (host->memory_budget_bytes != UINT64_C(0)) {
    report_derived_limits(&store->limits);
  }
  status = boot_generation_from_log(
      store, store->canonical_log_path, store->space_id, true, &generation,
      &log_length, error, error_capacity);
  if (status == FRAM_SERVER_OK) {
    store->current = generation;
    status = repair_log_tail(store, log_length,
                             (int64_t)generation->result.field_3, error,
                             error_capacity);
  }
  if (status == FRAM_SERVER_OK) {
    status = vector_length(generation->result.field_4, 0u, SIZE_MAX,
                           &append_length, error, error_capacity,
                           "generated boot append is not byte-valued");
  }
  if (status == FRAM_SERVER_OK && append_length != 0u) {
    status = append_log_vector(store, generation->result.field_4, false,
                               error, error_capacity);
  }
  if (status == FRAM_SERVER_OK) {
    status = store->host.storage_sync(store->host.context, error,
                                      error_capacity);
  }
  if (status != FRAM_SERVER_OK) {
    goto boot_failed;
  }
  store->compaction_base_bytes = generation->chain_reserved_bytes;
  store->compaction_base_generations = generation->chain_generations;
  *store_out = store;
  return FRAM_SERVER_OK;

boot_failed:
  if (generation != NULL) {
    generation_release(generation);
  }
  free(store->space_id);
  free(store->canonical_log_path);
  free(store);
  return status;
}

#ifndef FRAM_WASM_HOST_IMPORTS
#define FRAM_SERVER_SNAPSHOT_SUFFIX ".snapshot"

static char *snapshot_path_of(const char *canonical_log_path, char *error,
                              size_t error_capacity) {
  size_t length = strlen(canonical_log_path);
  size_t suffix = strlen(FRAM_SERVER_SNAPSHOT_SUFFIX);
  char *path;

  if (length > SIZE_MAX - suffix - 1u) {
    copy_error(error, error_capacity, "snapshot image path overflowed");
    return NULL;
  }
  path = malloc(length + suffix + 1u);
  if (path == NULL) {
    copy_error(error, error_capacity, "cannot allocate the snapshot path");
    return NULL;
  }
  memcpy(path, canonical_log_path, length);
  memcpy(path + length, FRAM_SERVER_SNAPSHOT_SUFFIX, suffix + 1u);
  return path;
}

int fram_server_store_boot(const char *canonical_log_path,
                           const char *space_id,
                           uint64_t memory_budget_bytes,
                           fram_server_store **store_out, char *error,
                           size_t error_capacity) {
  posix_storage *storage = NULL;
  posix_storage *snapshot_storage = NULL;
  fram_server_host_v1 host;
  char *snapshot_path;
  char close_error[FRAM_SERVER_ERROR_CAPACITY];
  int status;

  clear_error(error, error_capacity);
  if (store_out == NULL || canonical_log_path == NULL) {
    copy_error(error, error_capacity,
               "generated store boot requires a log path and output owner");
    return FRAM_SERVER_FATAL;
  }
  *store_out = NULL;
  status = posix_storage_open(canonical_log_path, &storage, error,
                              error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  snapshot_path = snapshot_path_of(canonical_log_path, error, error_capacity);
  if (snapshot_path == NULL) {
    (void)posix_storage_close(storage, close_error, sizeof(close_error));
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  status = posix_storage_open(snapshot_path, &snapshot_storage, error,
                              error_capacity);
  free(snapshot_path);
  if (status != FRAM_SERVER_OK) {
    (void)posix_storage_close(storage, close_error, sizeof(close_error));
    return status;
  }
  host = (fram_server_host_v1){
      .abi_version = FRAM_SERVER_HOST_ABI,
      .struct_size = (uint32_t)sizeof(host),
      .context = storage,
      .snapshot_context = snapshot_storage,
      .memory_budget_bytes = memory_budget_bytes,
      .clock_milliseconds = posix_realtime_milliseconds,
      .storage_size = posix_storage_size,
      .storage_read = posix_storage_read,
      .storage_truncate = posix_storage_truncate,
      .storage_append = posix_storage_append,
      .storage_sync = posix_storage_sync,
      .storage_close = posix_storage_close,
  };
  status = fram_server_store_boot_with_host(
      canonical_log_path, space_id, &host, store_out, error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    (void)posix_storage_close(storage, close_error, sizeof(close_error));
    (void)posix_storage_close(snapshot_storage, close_error,
                              sizeof(close_error));
  }
  return status;
}
#endif

/* The generated encoder reads the dispatch result in place, so this must run
   while the arenas that result points into are still live: inside dispatch,
   before the request owner or base generation can be released. */
static int encode_response_frame(
    const fram_server_store_dispatch_return *result, uint8_t **bytes_out,
    size_t *length_out, char *error, size_t error_capacity) {
  generated_owner *owner;
  fram_server_codec_write_response_return generated_result;
  uint8_t *bytes;
  size_t length;
  size_t index;
  int status;

  *bytes_out = NULL;
  *length_out = 0u;
  owner = owner_create(FRAM_SERVER_DEFAULT_ARENA_GROWTH_BYTES, error,
                       error_capacity);
  if (owner == NULL) {
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  generated_result = FRAM_SERVER_CALL_CODEC_WRITE_RESPONSE(
      &owner->arena, &owner->capability, *result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated response encode failed");
  if (status == FRAM_SERVER_OK) {
    status = vector_length(
        generated_result.field_1, FRAM_SERVER_FRAME_HEADER_BYTES,
        FRAM_SERVER_FRAME_MAX_BYTES, &length, error, error_capacity,
        "generated response frame has an invalid byte representation");
  }
  bytes = NULL;
  if (status == FRAM_SERVER_OK) {
    bytes = malloc(length);
    if (bytes == NULL) {
      copy_error(error, error_capacity,
                 "cannot allocate the encoded response frame");
      status = FRAM_SERVER_OUT_OF_MEMORY;
    }
  }
  for (index = 0u; status == FRAM_SERVER_OK && index < length; index += 1u) {
    const int64_t *value = native_vec_at(generated_result.field_1,
                                         (int64_t)index, INT64_C(8));

    if (*value < INT64_C(0) || *value > INT64_C(255)) {
      copy_error(error, error_capacity,
                 "generated response frame has an invalid byte representation");
      status = FRAM_SERVER_FATAL;
    } else {
      bytes[index] = (uint8_t)*value;
    }
  }
  owner_release(owner);
  if (status != FRAM_SERVER_OK) {
    free(bytes);
    return status;
  }
  *bytes_out = bytes;
  *length_out = length;
  return FRAM_SERVER_OK;
}

int fram_server_store_dispatch(fram_server_store *store,
                                   const fram_server_request *request,
                                   fram_server_response **response_out,
                                   char *error, size_t error_capacity) {
  fram_server_response *response;
  generated_store_generation *base_generation;
  generated_store_generation *next_generation = NULL;
  fram_server_store_dispatch_return result;
  fram_server_store_dispatch_arg_2 now_milliseconds;
  int64_t clock_milliseconds;
  uint8_t *bytes = NULL;
  size_t length = 0u;
  size_t append_length;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL || request == NULL || response_out == NULL) {
    copy_error(error, error_capacity,
               "generated dispatch requires owned input and output values");
    return FRAM_SERVER_FATAL;
  }
  *response_out = NULL;
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    return FRAM_SERVER_FATAL;
  }
  if (store_needs_compaction(store)) {
    status = compact_store(store, error, error_capacity);
    if (status != FRAM_SERVER_OK) {
      return status;
    }
  }
  status = store->host.clock_milliseconds(
      store->host.context, &clock_milliseconds, error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  now_milliseconds =
      (fram_server_store_dispatch_arg_2)clock_milliseconds;
  response = malloc(sizeof(*response));
  if (response == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated response wrapper");
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  /* The base generation and the request owner stay live for the whole call:
     the store holds its own reference to the base (directly, or through the
     replacement generation's parent chain after the swap below), and the
     caller owns the request. Only a state change takes new references, inside
     generation_create. */
  base_generation = store->current;
  result = FRAM_SERVER_CALL_STORE_DISPATCH(
      &request->owner->arena, &request->owner->capability,
      base_generation->result, request->result, now_milliseconds);
  status = generated_status((int64_t)result.field_0, error,
                            error_capacity,
                            "generated store dispatch failed");
  if (status == FRAM_SERVER_OK) {
    status = vector_length(result.field_3, 0u, SIZE_MAX,
                           &append_length, error, error_capacity,
                           "generated dispatch append is not byte-valued");
  }
  if (status == FRAM_SERVER_OK && append_length != 0u &&
      !result.field_5) {
    copy_error(error, error_capacity,
               "generated dispatch appended without changing state");
    status = FRAM_SERVER_FATAL;
  }
  if (status == FRAM_SERVER_OK && result.field_5) {
    next_generation = generation_create(
        request->owner, base_generation, result.field_4, error,
        error_capacity);
    if (next_generation == NULL) {
      status = FRAM_SERVER_FATAL;
    }
  }
  if (status == FRAM_SERVER_OK && append_length != 0u) {
    status = append_log_vector(store, result.field_3, true, error,
                               error_capacity);
    if (status != FRAM_SERVER_OK) {
      store->poisoned = true;
    }
  }
  if (status == FRAM_SERVER_OK && next_generation != NULL) {
    generated_store_generation *previous = store->current;

    store->current = next_generation;
    next_generation = NULL;
    generation_release(previous);
  }
  /* The image is a separate storage object; a failed image write never
     poisons the FRAMLOG, which stays the authoritative history. */
  if (status == FRAM_SERVER_OK) {
    status = write_snapshot_vector(store, result.field_6, error,
                                   error_capacity);
  }
  if (status == FRAM_SERVER_OK) {
    status = encode_response_frame(&result, &bytes, &length, error,
                                   error_capacity);
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_RESPONSE(
      &request->owner->arena, &request->owner->capability, result);
  if (status != FRAM_SERVER_OK) {
    if (next_generation != NULL) {
      generation_release(next_generation);
    }
    free(response);
    return status;
  }
  response->bytes = bytes;
  response->length = length;
  *response_out = response;
  return FRAM_SERVER_OK;
}

int fram_server_store_shutdown(fram_server_store *store, char *error,
                               size_t error_capacity) {
  fram_server_store_shutdown_return generated_result;
  int close_status;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL) {
    copy_error(error, error_capacity,
               "generated store shutdown requires an owned store");
    return FRAM_SERVER_FATAL;
  }
  generated_result = FRAM_SERVER_CALL_STORE_SHUTDOWN(
      &store->current->owner->arena, &store->current->owner->capability,
      store->current->result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated store shutdown failed");
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    status = FRAM_SERVER_FATAL;
  }
  close_status = store->host.storage_sync(store->host.context, error,
                                          error_capacity);
  if (close_status != FRAM_SERVER_OK) {
    status = close_status;
  }
  close_status = store->host.storage_close(store->host.context, error,
                                           error_capacity);
  if (close_status != FRAM_SERVER_OK) {
    status = close_status;
  }
  if (store->host.snapshot_context != NULL) {
    close_status = store->host.storage_close(store->host.snapshot_context,
                                             error, error_capacity);
    if (close_status != FRAM_SERVER_OK) {
      status = close_status;
    }
  }
  generation_release(store->current);
  free(store->space_id);
  free(store->canonical_log_path);
  free(store);
  return status;
}

int fram_server_codec_decode_request(const uint8_t *bytes, size_t length,
                                     fram_server_request **request_out,
                                     char *error, size_t error_capacity) {
  fram_server_request *request;
  generated_owner *owner;
  native_byte_source *borrowed = NULL;
  uint32_t body_length;
  int status;

  clear_error(error, error_capacity);
  if (request_out == NULL || (bytes == NULL && length != 0u)) {
    copy_error(error, error_capacity,
               "generated request decode requires bytes and an output owner");
    return FRAM_SERVER_FATAL;
  }
  *request_out = NULL;
  if (length < FRAM_SERVER_FRAME_HEADER_BYTES) {
    copy_error(error, error_capacity,
               "generated request frame ended inside its header");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  body_length = frame_body_length(bytes);
  if (body_length > FRAM_SERVER_FRAME_MAX_BODY_BYTES) {
    copy_error(error, error_capacity,
               "generated request frame exceeds the body limit");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  if (length != FRAM_SERVER_FRAME_HEADER_BYTES + (size_t)body_length) {
    copy_error(error, error_capacity,
               length < FRAM_SERVER_FRAME_HEADER_BYTES + (size_t)body_length
                   ? "generated request frame ended inside its body"
                   : "generated request frame has trailing bytes");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  /* No store is in scope at decode time, so a scratch owner keeps the default
     growth floor even when a store elsewhere derives one from a budget. */
  owner = owner_create(FRAM_SERVER_DEFAULT_ARENA_GROWTH_BYTES, error,
                       error_capacity);
  if (owner == NULL) {
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  request = malloc(sizeof(*request));
  if (request == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request wrapper");
    owner_release(owner);
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  request->owner = owner;
  if (!borrow_bytes(&owner->arena, bytes, length, &borrowed, error,
                    error_capacity)) {
    owner_release(owner);
    free(request);
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  request->result = FRAM_SERVER_CALL_CODEC_READ_REQUEST(
      &owner->arena, &owner->capability, borrowed);
  status = generated_status((int64_t)request->result.field_0, error,
                            error_capacity,
                            "generated request decode failed");
  if (status != FRAM_SERVER_OK) {
    (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
        &owner->arena, &owner->capability, request->result);
    owner_release(owner);
    free(request);
    return FRAM_SERVER_CLIENT_ERROR;
  }
  *request_out = request;
  return FRAM_SERVER_OK;
}

int fram_server_codec_encode_response(const fram_server_response *response,
                                      uint8_t **bytes_out,
                                      size_t *length_out, char *error,
                                      size_t error_capacity) {
  uint8_t *bytes;

  clear_error(error, error_capacity);
  if (response == NULL || bytes_out == NULL || length_out == NULL) {
    copy_error(error, error_capacity,
               "generated response encode requires owned input and output values");
    return FRAM_SERVER_FATAL;
  }
  *bytes_out = NULL;
  *length_out = 0u;
  /* Dispatch already encoded the frame; its length is at least the frame
     header, so this allocation is never zero-sized. */
  bytes = malloc(response->length);
  if (bytes == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the encoded response frame");
    return FRAM_SERVER_OUT_OF_MEMORY;
  }
  memcpy(bytes, response->bytes, response->length);
  *bytes_out = bytes;
  *length_out = response->length;
  return FRAM_SERVER_OK;
}

void fram_server_codec_release_bytes(uint8_t *bytes) { free(bytes); }

int fram_server_codec_read_request(int client_fd,
                                   fram_server_request **request_out,
                                   char *error, size_t error_capacity) {
  uint8_t *frame;
  size_t frame_length;
  int status;

  clear_error(error, error_capacity);
  if (request_out == NULL) {
    copy_error(error, error_capacity,
               "generated request read requires an output owner");
    return FRAM_SERVER_FATAL;
  }
  *request_out = NULL;
  status = read_frame(client_fd, &frame, &frame_length, error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  status = fram_server_codec_decode_request(
      frame, frame_length, request_out, error, error_capacity);
  free(frame);
  return status;
}

int fram_server_codec_write_response(
    int client_fd, const fram_server_response *response, char *error,
    size_t error_capacity) {
  clear_error(error, error_capacity);
  if (response == NULL) {
    copy_error(error, error_capacity,
               "generated response write requires an owned response");
    return FRAM_SERVER_FATAL;
  }
  return write_bytes(client_fd, response->bytes, response->length, error,
                     error_capacity);
}

void fram_server_codec_release_request(fram_server_request *request) {
  if (request == NULL) {
    return;
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
      &request->owner->arena, &request->owner->capability, request->result);
  owner_release(request->owner);
  free(request);
}

void fram_server_codec_release_response(
    fram_server_response *response) {
  if (response == NULL) {
    return;
  }
  free(response->bytes);
  free(response);
}
