// SPDX-License-Identifier: MIT OR Apache-2.0
#define _POSIX_C_SOURCE 200809L

#include "server_host.h"
#include "server_symbols.h"

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#define FRAM_SERVER_ADAPTER_ABI 1u
#define FRAM_SERVER_ARENA_BASE_BYTES ((size_t)(64u * 1024u * 1024u))
#define FRAM_SERVER_CAPABILITY_TOKEN UINT64_C(1)
#define FRAM_SERVER_FRAME_HEADER_BYTES ((size_t)26u)
#define FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET ((size_t)14u)
#define FRAM_SERVER_FRAME_MAX_BODY_BYTES UINT32_C(1048576)
#define FRAM_SERVER_FRAME_MAX_BYTES ((size_t)1048602u)
#define FRAM_SERVER_IO_CHUNK_BYTES ((size_t)8192u)

_Static_assert(FRAM_SERVER_ADAPTER_ABI ==
                   FRAM_SERVER_GENERATED_ABI,
               "server adapter ABI version");
_Static_assert(INT_MAX >= INT32_MAX, "generated status fits host int");
_Static_assert(sizeof(((native_capability *)0)->token) == sizeof(uint64_t),
               "native capability token ABI");
_Static_assert(sizeof(fram_server_generated_abi_return) == sizeof(int64_t),
               "generated ABI result width");
_Static_assert(sizeof(fram_server_store_boot_arg_0) == sizeof(uint64_t),
               "generated log-path Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_1) == sizeof(uint64_t),
               "generated space-id Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_2) ==
                   sizeof(native_vec *),
               "generated log byte-vector ABI");
_Static_assert(sizeof(fram_server_codec_read_request_arg_0) ==
                   sizeof(native_vec *),
               "generated request byte-vector ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_0) ==
                   sizeof(int64_t),
               "generated StoreResult status ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_3) ==
                   sizeof(int64_t),
               "generated StoreResult valid-log ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_4) ==
                   sizeof(native_vec *),
               "generated StoreResult boot-append ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated ResponseResult status ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_3) ==
        sizeof(native_vec *),
    "generated ResponseResult append ABI");
_Static_assert(sizeof(fram_server_store_dispatch_arg_2) == sizeof(int64_t),
               "generated dispatch clock ABI");
_Static_assert(
    sizeof(((fram_server_store_shutdown_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated shutdown Status ABI");
_Static_assert(
    sizeof(((fram_server_codec_read_request_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated RequestResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated BytesResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_1) ==
        sizeof(native_vec *),
    "generated BytesResult vector ABI");

typedef struct generated_owner {
  size_t references;
  native_arena arena;
  native_capability capability;
  uint8_t *storage;
} generated_owner;

struct fram_server_store {
  generated_owner *owner;
  fram_server_store_boot_return result;
  int log_fd;
  bool poisoned;
};

struct fram_server_request {
  generated_owner *owner;
  fram_server_codec_read_request_return result;
};

struct fram_server_response {
  generated_owner *store_owner;
  generated_owner *request_owner;
  fram_server_store_dispatch_return result;
};

static void clear_error(char *error, size_t error_capacity) {
  if (error != NULL && error_capacity != 0u) {
    error[0] = '\0';
  }
}

static void copy_error(char *error, size_t error_capacity,
                       const char *detail) {
  size_t length;
  size_t copied;

  if (error == NULL || error_capacity == 0u) {
    return;
  }
  length = strlen(detail);
  copied = length < error_capacity - 1u ? length : error_capacity - 1u;
  if (copied != 0u) {
    memcpy(error, detail, copied);
  }
  error[copied] = '\0';
}

static generated_owner *owner_create(size_t input_byte_count, char *error,
                                     size_t error_capacity) {
  generated_owner *owner;
  size_t input_storage_bytes;
  size_t capacity;

  if (input_byte_count >
      (SIZE_MAX - FRAM_SERVER_ARENA_BASE_BYTES) / sizeof(int64_t)) {
    copy_error(error, error_capacity,
               "generated input exceeds the native arena address space");
    return NULL;
  }
  input_storage_bytes = input_byte_count * sizeof(int64_t);
  capacity = FRAM_SERVER_ARENA_BASE_BYTES + input_storage_bytes;
  owner = malloc(sizeof(*owner));
  if (owner == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated owner");
    return NULL;
  }
  owner->storage = malloc(capacity);
  if (owner->storage == NULL) {
    free(owner);
    copy_error(error, error_capacity,
               "cannot allocate the generated Beagle arena");
    return NULL;
  }
  owner->references = 1u;
  native_arena_init(&owner->arena, owner->storage, capacity);
  owner->capability.token = FRAM_SERVER_CAPABILITY_TOKEN;
  return owner;
}

static void owner_retain(generated_owner *owner) {
  // Store-owner calls serialize; request owners remain local to one worker.
  owner->references += 1u;
}

static void owner_release(generated_owner *owner) {
  owner->references -= 1u;
  if (owner->references == 0u) {
    free(owner->storage);
    free(owner);
  }
}

static uint64_t native_text_from_c(native_arena *arena, const char *text) {
  size_t length = strlen(text);
  uint8_t *destination = NULL;
  uint64_t result = native_text_alloc(arena, (uint64_t)length, &destination);

  if (length != 0u) {
    memcpy(destination, text, length);
  }
  return result;
}

static native_vec *native_byte_vector(generated_owner *owner,
                                      const uint8_t *bytes, size_t length) {
  native_vec *vector = native_vec_new(&owner->arena, (int64_t)length,
                                      INT64_C(8), _Alignof(int64_t));
  size_t index;

  for (index = 0u; index < length; index += 1u) {
    int64_t value = (int64_t)bytes[index];
    vector = native_vec_push(&owner->arena, vector, &value, INT64_C(8),
                             _Alignof(int64_t));
  }
  return vector;
}

static int generated_status(int64_t status, char *error,
                            size_t error_capacity,
                            const char *failure_detail) {
  if (status == (int64_t)FRAM_SERVER_OK) {
    return FRAM_SERVER_OK;
  }
  copy_error(error, error_capacity, failure_detail);
  return FRAM_SERVER_FATAL;
}

static int realtime_milliseconds(int64_t *milliseconds_out, char *error,
                                 size_t error_capacity) {
  struct timespec now;

  if (clock_gettime(CLOCK_REALTIME, &now) != 0 || now.tv_sec < (time_t)0 ||
      now.tv_nsec < 0 || now.tv_nsec >= 1000000000L ||
      (uintmax_t)now.tv_sec > (uintmax_t)(INT64_MAX / INT64_C(1000))) {
    copy_error(error, error_capacity,
               "cannot read a bounded realtime dispatch clock");
    return FRAM_SERVER_FATAL;
  }
  *milliseconds_out =
      (int64_t)now.tv_sec * INT64_C(1000) + (int64_t)(now.tv_nsec / 1000000L);
  return FRAM_SERVER_OK;
}

static int read_exact(int fd, uint8_t *destination, size_t length,
                      bool clean_eof_is_peer_closed,
                      int failure_status,
                      const char *truncated_detail, const char *read_detail,
                      char *error, size_t error_capacity) {
  size_t position = 0u;

  while (position < length) {
    ssize_t count = read(fd, destination + position, length - position);

    if (count > 0) {
      position += (size_t)count;
      continue;
    }
    if (count == 0) {
      if (position == 0u && clean_eof_is_peer_closed) {
        return FRAM_SERVER_PEER_CLOSED;
      }
      copy_error(error, error_capacity, truncated_detail);
      return failure_status;
    }
    if (errno == EINTR) {
      continue;
    }
    copy_error(error, error_capacity, read_detail);
    return failure_status;
  }
  return FRAM_SERVER_OK;
}

static int read_log(const char *path, int *fd_out, uint8_t **bytes_out,
                    size_t *length_out, char *error,
                    size_t error_capacity) {
  struct stat status;
  uint8_t *bytes = NULL;
  int fd = open(path, O_RDWR | O_CLOEXEC);
  size_t length;
  int read_status;

  if (fd < 0) {
    copy_error(error, error_capacity, "cannot open the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  if (fstat(fd, &status) != 0 || !S_ISREG(status.st_mode) ||
      status.st_size < 0 || (uintmax_t)status.st_size > (uintmax_t)SIZE_MAX ||
      (uintmax_t)status.st_size > (uintmax_t)INT64_MAX) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is not a readable regular file");
    (void)close(fd);
    return FRAM_SERVER_FATAL;
  }
  length = (size_t)status.st_size;
  if (length != 0u) {
    bytes = malloc(length);
    if (bytes == NULL) {
      copy_error(error, error_capacity,
                 "cannot allocate the canonical FRAMLOG input");
      (void)close(fd);
      return FRAM_SERVER_FATAL;
    }
  }
  read_status = read_exact(fd, bytes, length, false, FRAM_SERVER_FATAL,
                           "canonical FRAMLOG ended while reading",
                           "cannot read the canonical FRAMLOG", error,
                           error_capacity);
  if (read_status != FRAM_SERVER_OK) {
    free(bytes);
    (void)close(fd);
    return read_status;
  }
  *fd_out = fd;
  *bytes_out = bytes;
  *length_out = length;
  return FRAM_SERVER_OK;
}

static int vector_length(const native_vec *vector, size_t minimum,
                         size_t maximum, size_t *length_out, char *error,
                         size_t error_capacity,
                         const char *invalid_detail) {
  int64_t length;

  if (vector == NULL) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  length = native_vec_length(vector);
  if (length < INT64_C(0) || (uint64_t)length > (uint64_t)SIZE_MAX ||
      (size_t)length < minimum || (size_t)length > maximum) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  *length_out = (size_t)length;
  return FRAM_SERVER_OK;
}

static int write_vector(int fd, const native_vec *vector, size_t minimum,
                        size_t maximum, bool peer_close_is_status,
                        int write_failure_status,
                        size_t *length_out, char *error,
                        size_t error_capacity, const char *invalid_detail,
                        const char *write_detail) {
  uint8_t chunk[FRAM_SERVER_IO_CHUNK_BYTES];
  size_t length;
  size_t offset = 0u;
  int status = vector_length(vector, minimum, maximum, &length, error,
                             error_capacity, invalid_detail);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  while (offset < length) {
    size_t count = length - offset;
    size_t index;
    size_t written = 0u;

    if (count > sizeof(chunk)) {
      count = sizeof(chunk);
    }
    for (index = 0u; index < count; index += 1u) {
      const int64_t *value = native_vec_at(
          vector, (int64_t)(offset + index), INT64_C(8));

      if (*value < INT64_C(0) || *value > INT64_C(255)) {
        copy_error(error, error_capacity, invalid_detail);
        return FRAM_SERVER_FATAL;
      }
      chunk[index] = (uint8_t)*value;
    }
    while (written < count) {
      ssize_t result = write(fd, chunk + written, count - written);

      if (result > 0) {
        written += (size_t)result;
        continue;
      }
      if (result < 0 && errno == EINTR) {
        continue;
      }
      if (peer_close_is_status && result < 0 &&
          (errno == EPIPE || errno == ECONNRESET)) {
        return FRAM_SERVER_PEER_CLOSED;
      }
      copy_error(error, error_capacity, write_detail);
      return write_failure_status;
    }
    offset += count;
  }
  if (length_out != NULL) {
    *length_out = length;
  }
  return FRAM_SERVER_OK;
}

static int append_log_vector(fram_server_store *store,
                             const native_vec *vector, bool sync_after_write,
                             char *error, size_t error_capacity) {
  size_t length;
  int status = vector_length(vector, 0u, SIZE_MAX, &length, error,
                             error_capacity,
                             "generated FRAMLOG append is not byte-valued");

  if (status != FRAM_SERVER_OK || length == 0u) {
    return status;
  }
  if (lseek(store->log_fd, (off_t)0, SEEK_END) < (off_t)0) {
    copy_error(error, error_capacity, "cannot seek the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  status = write_vector(store->log_fd, vector, 0u, SIZE_MAX, false,
                        FRAM_SERVER_FATAL, NULL, error, error_capacity,
                        "generated FRAMLOG append is not byte-valued",
                        "cannot append the canonical FRAMLOG");
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  if (sync_after_write && fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  return FRAM_SERVER_OK;
}

static int repair_log_tail(fram_server_store *store,
                           size_t original_length, int64_t valid_length,
                           char *error, size_t error_capacity) {
  off_t valid_offset;

  if (valid_length < INT64_C(0) ||
      (uint64_t)valid_length > (uint64_t)original_length) {
    copy_error(error, error_capacity,
               "generated FRAMLOG recovery returned an invalid prefix");
    return FRAM_SERVER_FATAL;
  }
  if ((size_t)valid_length == original_length) {
    return FRAM_SERVER_OK;
  }
  valid_offset = (off_t)valid_length;
  if ((int64_t)valid_offset != valid_length ||
      ftruncate(store->log_fd, valid_offset) != 0) {
    copy_error(error, error_capacity,
               "cannot repair the canonical FRAMLOG tail");
    return FRAM_SERVER_FATAL;
  }
  return FRAM_SERVER_OK;
}

static uint32_t frame_body_length(const uint8_t *header) {
  return (uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET] |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 1u]
          << 8u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 2u]
          << 16u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 3u]
          << 24u);
}

static int read_frame(int fd, uint8_t **frame_out, size_t *length_out,
                      char *error, size_t error_capacity) {
  uint8_t header[FRAM_SERVER_FRAME_HEADER_BYTES];
  uint8_t *frame;
  uint32_t body_length;
  size_t frame_length;
  int status = read_exact(
      fd, header, sizeof(header), true, FRAM_SERVER_CLIENT_ERROR,
      "generated request frame ended inside its header",
      "cannot read the generated request frame header", error,
      error_capacity);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  body_length = frame_body_length(header);
  if (body_length > FRAM_SERVER_FRAME_MAX_BODY_BYTES) {
    copy_error(error, error_capacity,
               "generated request frame exceeds the body limit");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  frame_length = sizeof(header) + (size_t)body_length;
  frame = malloc(frame_length);
  if (frame == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request frame");
    return FRAM_SERVER_FATAL;
  }
  memcpy(frame, header, sizeof(header));
  status = read_exact(fd, frame + sizeof(header), (size_t)body_length, false,
                      FRAM_SERVER_CLIENT_ERROR,
                      "generated request frame ended inside its body",
                      "cannot read the generated request frame body", error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    free(frame);
    return status;
  }
  *frame_out = frame;
  *length_out = frame_length;
  return FRAM_SERVER_OK;
}

uint32_t fram_server_generated_abi(void) {
  generated_owner *owner = owner_create(0u, NULL, 0u);
  fram_server_generated_abi_return result;

  if (owner == NULL) {
    return UINT32_C(0);
  }
  result = FRAM_SERVER_CALL_GENERATED_ABI(&owner->arena,
                                              &owner->capability);
  owner_release(owner);
  if ((int64_t)result < INT64_C(0) ||
      (int64_t)result > (int64_t)UINT32_MAX) {
    return UINT32_C(0);
  }
  return (uint32_t)result;
}

int fram_server_store_boot(const char *canonical_log_path,
                               const char *space_id,
                               fram_server_store **store_out, char *error,
                               size_t error_capacity) {
  fram_server_store *store;
  generated_owner *owner;
  uint8_t *log_bytes;
  size_t log_length;
  int log_fd;
  fram_server_store_boot_arg_0 generated_log_path;
  fram_server_store_boot_arg_1 generated_space_id;
  fram_server_store_boot_arg_2 generated_log;
  int status;

  clear_error(error, error_capacity);
  if (store_out == NULL || canonical_log_path == NULL) {
    copy_error(error, error_capacity,
               "generated store boot requires a log path and output owner");
    return FRAM_SERVER_FATAL;
  }
  *store_out = NULL;
  status = read_log(canonical_log_path, &log_fd, &log_bytes, &log_length,
                    error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  owner = owner_create(log_length, error, error_capacity);
  if (owner == NULL) {
    free(log_bytes);
    (void)close(log_fd);
    return FRAM_SERVER_FATAL;
  }
  store = malloc(sizeof(*store));
  if (store == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated store wrapper");
    free(log_bytes);
    owner_release(owner);
    (void)close(log_fd);
    return FRAM_SERVER_FATAL;
  }
  store->owner = owner;
  store->log_fd = log_fd;
  store->poisoned = false;
  generated_log_path = native_text_from_c(&owner->arena, canonical_log_path);
  generated_space_id =
      native_text_from_c(&owner->arena, space_id != NULL ? space_id : "");
  generated_log = native_byte_vector(owner, log_bytes, log_length);
  free(log_bytes);

  store->result = FRAM_SERVER_CALL_STORE_BOOT(
      &owner->arena, &owner->capability, generated_log_path,
      generated_space_id, generated_log);
  status = generated_status((int64_t)store->result.field_0, error,
                            error_capacity, "generated store boot failed");
  if (status == FRAM_SERVER_OK) {
    status = repair_log_tail(store, log_length,
                             (int64_t)store->result.field_3, error,
                             error_capacity);
  }
  if (status == FRAM_SERVER_OK) {
    status = append_log_vector(store, store->result.field_4, false, error,
                               error_capacity);
  }
  if (status == FRAM_SERVER_OK && fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  if (status != FRAM_SERVER_OK) {
    (void)close(store->log_fd);
    owner_release(store->owner);
    free(store);
    return FRAM_SERVER_FATAL;
  }
  *store_out = store;
  return FRAM_SERVER_OK;
}

int fram_server_store_dispatch(fram_server_store *store,
                                   const fram_server_request *request,
                                   fram_server_response **response_out,
                                   char *error, size_t error_capacity) {
  fram_server_response *response;
  fram_server_store_dispatch_arg_2 now_milliseconds;
  int64_t clock_milliseconds;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL || request == NULL || response_out == NULL) {
    copy_error(error, error_capacity,
               "generated dispatch requires owned input and output values");
    return FRAM_SERVER_FATAL;
  }
  *response_out = NULL;
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    return FRAM_SERVER_FATAL;
  }
  status = realtime_milliseconds(&clock_milliseconds, error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  now_milliseconds =
      (fram_server_store_dispatch_arg_2)clock_milliseconds;
  response = malloc(sizeof(*response));
  if (response == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated response wrapper");
    return FRAM_SERVER_FATAL;
  }
  response->result = FRAM_SERVER_CALL_STORE_DISPATCH(
      &store->owner->arena, &store->owner->capability, store->result,
      request->result, now_milliseconds);
  status = generated_status((int64_t)response->result.field_0, error,
                            error_capacity,
                            "generated store dispatch failed");
  if (status == FRAM_SERVER_OK) {
    status = append_log_vector(store, response->result.field_3, true, error,
                               error_capacity);
    if (status != FRAM_SERVER_OK) {
      store->poisoned = true;
    }
  }
  if (status != FRAM_SERVER_OK) {
    (void)FRAM_SERVER_CALL_CODEC_RELEASE_RESPONSE(
        &store->owner->arena, &store->owner->capability, response->result);
    free(response);
    return FRAM_SERVER_FATAL;
  }
  owner_retain(store->owner);
  owner_retain(request->owner);
  response->store_owner = store->owner;
  response->request_owner = request->owner;
  *response_out = response;
  return FRAM_SERVER_OK;
}

int fram_server_store_shutdown(fram_server_store *store, char *error,
                                   size_t error_capacity) {
  fram_server_store_shutdown_return generated_result;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL) {
    copy_error(error, error_capacity,
               "generated store shutdown requires an owned store");
    return FRAM_SERVER_FATAL;
  }
  generated_result = FRAM_SERVER_CALL_STORE_SHUTDOWN(
      &store->owner->arena, &store->owner->capability, store->result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated store shutdown failed");
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    status = FRAM_SERVER_FATAL;
  }
  if (fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  if (close(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot close the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  owner_release(store->owner);
  free(store);
  return status;
}

int fram_server_codec_read_request(int client_fd,
                                       fram_server_request **request_out,
                                       char *error, size_t error_capacity) {
  fram_server_request *request;
  generated_owner *owner;
  uint8_t *frame;
  size_t frame_length;
  fram_server_codec_read_request_arg_0 generated_frame;
  int status;

  clear_error(error, error_capacity);
  if (request_out == NULL) {
    copy_error(error, error_capacity,
               "generated request read requires an output owner");
    return FRAM_SERVER_FATAL;
  }
  *request_out = NULL;
  status = read_frame(client_fd, &frame, &frame_length, error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  owner = owner_create(frame_length, error, error_capacity);
  if (owner == NULL) {
    free(frame);
    return FRAM_SERVER_FATAL;
  }
  request = malloc(sizeof(*request));
  if (request == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request wrapper");
    free(frame);
    owner_release(owner);
    return FRAM_SERVER_FATAL;
  }
  request->owner = owner;
  generated_frame = native_byte_vector(owner, frame, frame_length);
  free(frame);
  request->result = FRAM_SERVER_CALL_CODEC_READ_REQUEST(
      &owner->arena, &owner->capability, generated_frame);
  status = generated_status((int64_t)request->result.field_0, error,
                            error_capacity,
                            "generated request decode failed");
  if (status != FRAM_SERVER_OK) {
    (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
        &owner->arena, &owner->capability, request->result);
    owner_release(owner);
    free(request);
    return FRAM_SERVER_CLIENT_ERROR;
  }
  *request_out = request;
  return FRAM_SERVER_OK;
}

int fram_server_codec_write_response(
    int client_fd, const fram_server_response *response, char *error,
    size_t error_capacity) {
  generated_owner *owner;
  fram_server_codec_write_response_return generated_result;
  int status;

  clear_error(error, error_capacity);
  if (response == NULL) {
    copy_error(error, error_capacity,
               "generated response write requires an owned response");
    return FRAM_SERVER_FATAL;
  }
  owner = owner_create(0u, error, error_capacity);
  if (owner == NULL) {
    return FRAM_SERVER_FATAL;
  }
  generated_result = FRAM_SERVER_CALL_CODEC_WRITE_RESPONSE(
      &owner->arena, &owner->capability, response->result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated response encode failed");
  if (status == FRAM_SERVER_OK) {
    status = write_vector(
        client_fd, generated_result.field_1,
        FRAM_SERVER_FRAME_HEADER_BYTES,
        FRAM_SERVER_FRAME_MAX_BYTES, true,
        FRAM_SERVER_CLIENT_ERROR, NULL, error, error_capacity,
        "generated response frame has an invalid byte representation",
        "cannot write the generated response frame");
  }
  owner_release(owner);
  return status;
}

void fram_server_codec_release_request(fram_server_request *request) {
  if (request == NULL) {
    return;
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
      &request->owner->arena, &request->owner->capability, request->result);
  owner_release(request->owner);
  free(request);
}

void fram_server_codec_release_response(
    fram_server_response *response) {
  if (response == NULL) {
    return;
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_RESPONSE(
      &response->store_owner->arena, &response->store_owner->capability,
      response->result);
  owner_release(response->request_owner);
  owner_release(response->store_owner);
  free(response);
}
