// SPDX-License-Identifier: MIT OR Apache-2.0
#define _POSIX_C_SOURCE 200809L

#include "server_host.h"
#include "server_symbols.h"

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#define FRAM_SERVER_ADAPTER_ABI 2u
#define FRAM_SERVER_ARENA_GROWTH_BYTES ((size_t)(64u * 1024u))
#define FRAM_SERVER_COMPACT_GENERATIONS ((size_t)256u)
#define FRAM_SERVER_COMPACT_INCREMENT_BYTES                            \
  ((size_t)(64u * 1024u * 1024u))
#define FRAM_SERVER_CAPABILITY_TOKEN UINT64_C(1)
#define FRAM_SERVER_FRAME_HEADER_BYTES ((size_t)26u)
#define FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET ((size_t)14u)
#define FRAM_SERVER_FRAME_MAX_BODY_BYTES UINT32_C(1048576)
#define FRAM_SERVER_FRAME_MAX_BYTES ((size_t)1048602u)
#define FRAM_SERVER_IO_CHUNK_BYTES ((size_t)8192u)

_Static_assert(FRAM_SERVER_ADAPTER_ABI ==
                   FRAM_SERVER_GENERATED_ABI,
               "server adapter ABI version");
_Static_assert(INT_MAX >= INT32_MAX, "generated status fits host int");
_Static_assert(sizeof(((native_capability *)0)->token) == sizeof(uint64_t),
               "native capability token ABI");
_Static_assert(sizeof(fram_server_generated_abi_return) == sizeof(int64_t),
               "generated ABI result width");
_Static_assert(sizeof(fram_server_store_boot_arg_0) == sizeof(uint64_t),
               "generated log-path Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_1) == sizeof(uint64_t),
               "generated space-id Text ABI");
_Static_assert(sizeof(fram_server_store_boot_arg_2) == sizeof(native_vec *),
               "generated log byte-vector ABI");
_Static_assert(sizeof(fram_server_codec_read_request_arg_0) ==
                   sizeof(native_vec *),
               "generated request byte-vector ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_0) ==
                   sizeof(int64_t),
               "generated StoreResult status ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_3) ==
                   sizeof(int64_t),
               "generated StoreResult valid-log ABI");
_Static_assert(sizeof(((fram_server_store_boot_return *)0)->field_4) ==
                   sizeof(native_vec *),
               "generated StoreResult boot-append ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated ResponseResult status ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_3) ==
        sizeof(native_vec *),
    "generated ResponseResult append ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_4) ==
        sizeof(fram_server_store_boot_return),
    "generated ResponseResult next-store ABI");
_Static_assert(
    sizeof(((fram_server_store_dispatch_return *)0)->field_5) ==
        sizeof(bool),
    "generated ResponseResult state-change ABI");
_Static_assert(sizeof(fram_server_store_dispatch_arg_2) == sizeof(int64_t),
               "generated dispatch clock ABI");
_Static_assert(
    sizeof(((fram_server_store_shutdown_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated shutdown Status ABI");
_Static_assert(
    sizeof(((fram_server_codec_read_request_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated RequestResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_0) ==
        sizeof(int64_t),
    "generated BytesResult status ABI");
_Static_assert(
    sizeof(((fram_server_codec_write_response_return *)0)->field_1) ==
        sizeof(native_vec *),
    "generated BytesResult vector ABI");

typedef struct generated_owner {
  _Atomic size_t references;
  native_arena arena;
  native_capability capability;
} generated_owner;

typedef struct generated_store_generation {
  _Atomic size_t references;
  generated_owner *owner;
  struct generated_store_generation *parent;
  fram_server_store_boot_return result;
  size_t chain_reserved_bytes;
  size_t chain_generations;
} generated_store_generation;

struct fram_server_store {
  generated_store_generation *current;
  char *canonical_log_path;
  char *space_id;
  int log_fd;
  bool poisoned;
  size_t compaction_base_bytes;
  size_t compaction_base_generations;
};

struct fram_server_request {
  generated_owner *owner;
  fram_server_codec_read_request_return result;
};

struct fram_server_response {
  generated_owner *scratch_owner;
  generated_store_generation *base_generation;
  fram_server_store_dispatch_return result;
};

static void clear_error(char *error, size_t error_capacity) {
  if (error != NULL && error_capacity != 0u) {
    error[0] = '\0';
  }
}

static void copy_error(char *error, size_t error_capacity,
                       const char *detail) {
  size_t length;
  size_t copied;

  if (error == NULL || error_capacity == 0u) {
    return;
  }
  length = strlen(detail);
  copied = length < error_capacity - 1u ? length : error_capacity - 1u;
  if (copied != 0u) {
    memcpy(error, detail, copied);
  }
  error[copied] = '\0';
}

static char *duplicate_string(const char *source, char *error,
                              size_t error_capacity) {
  size_t length = strlen(source);
  char *copy;

  if (length == SIZE_MAX) {
    copy_error(error, error_capacity, "generated string length overflowed");
    return NULL;
  }
  copy = malloc(length + 1u);
  if (copy == NULL) {
    copy_error(error, error_capacity, "cannot allocate generated host text");
    return NULL;
  }
  memcpy(copy, source, length + 1u);
  return copy;
}

static generated_owner *owner_create(char *error, size_t error_capacity) {
  generated_owner *owner;

  owner = malloc(sizeof(*owner));
  if (owner == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated owner");
    return NULL;
  }
  if (!native_arena_init_growable(&owner->arena,
                                  FRAM_SERVER_ARENA_GROWTH_BYTES)) {
    free(owner);
    copy_error(error, error_capacity,
               "cannot allocate the generated Beagle arena");
    return NULL;
  }
  atomic_init(&owner->references, (size_t)1u);
  owner->capability.token = FRAM_SERVER_CAPABILITY_TOKEN;
  return owner;
}

static void owner_retain(generated_owner *owner) {
  (void)atomic_fetch_add_explicit(&owner->references, (size_t)1u,
                                  memory_order_relaxed);
}

static void owner_release(generated_owner *owner) {
  if (atomic_fetch_sub_explicit(&owner->references, (size_t)1u,
                                memory_order_acq_rel) == (size_t)1u) {
    native_arena_destroy(&owner->arena);
    free(owner);
  }
}

static generated_store_generation *generation_create(
    generated_owner *owner, generated_store_generation *parent,
    fram_server_store_boot_return result, char *error,
    size_t error_capacity) {
  generated_store_generation *generation = malloc(sizeof(*generation));
  size_t own_reserved;

  if (generation == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated store generation");
    return NULL;
  }
  own_reserved = native_arena_reserved_bytes(&owner->arena);
  if (parent != NULL &&
      parent->chain_reserved_bytes > SIZE_MAX - own_reserved) {
    free(generation);
    copy_error(error, error_capacity,
               "generated store generation accounting overflowed");
    return NULL;
  }
  atomic_init(&generation->references, (size_t)1u);
  owner_retain(owner);
  generation->owner = owner;
  generation->parent = parent;
  if (parent != NULL) {
    (void)atomic_fetch_add_explicit(&parent->references, (size_t)1u,
                                    memory_order_relaxed);
  }
  generation->result = result;
  generation->chain_reserved_bytes =
      own_reserved + (parent == NULL ? 0u : parent->chain_reserved_bytes);
  generation->chain_generations =
      (size_t)1u + (parent == NULL ? 0u : parent->chain_generations);
  return generation;
}

static void generation_retain(generated_store_generation *generation) {
  (void)atomic_fetch_add_explicit(&generation->references, (size_t)1u,
                                  memory_order_relaxed);
}

static void generation_release(generated_store_generation *generation) {
  generated_store_generation *parent;

  if (atomic_fetch_sub_explicit(&generation->references, (size_t)1u,
                                memory_order_acq_rel) != (size_t)1u) {
    return;
  }
  parent = generation->parent;
  owner_release(generation->owner);
  free(generation);
  if (parent != NULL) {
    generation_release(parent);
  }
}

static uint64_t native_text_from_c(native_arena *arena, const char *text) {
  size_t length = strlen(text);
  uint8_t *destination = NULL;
  uint64_t result = native_text_alloc(arena, (uint64_t)length, &destination);

  if (length != 0u) {
    memcpy(destination, text, length);
  }
  return result;
}

typedef struct borrowed_byte_vector {
  native_vec vector;
  int64_t *elements;
} borrowed_byte_vector;

static bool borrowed_byte_vector_init(borrowed_byte_vector *borrowed,
                                      const uint8_t *bytes, size_t length,
                                      char *error, size_t error_capacity) {
  size_t index;

  if (length > (size_t)INT64_MAX ||
      length > SIZE_MAX / sizeof(*borrowed->elements)) {
    copy_error(error, error_capacity,
               "generated byte input exceeds the native vector range");
    return false;
  }
  borrowed->elements =
      length == 0u ? NULL : malloc(length * sizeof(*borrowed->elements));
  if (length != 0u && borrowed->elements == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated byte input bridge");
    return false;
  }
  for (index = 0u; index < length; index += 1u) {
    borrowed->elements[index] = (int64_t)bytes[index];
  }
  borrowed->vector.elements = borrowed->elements;
  borrowed->vector.length = (int64_t)length;
  borrowed->vector.capacity = (int64_t)length;
  return true;
}

static void borrowed_byte_vector_destroy(borrowed_byte_vector *borrowed) {
  free(borrowed->elements);
  borrowed->elements = NULL;
  borrowed->vector.elements = NULL;
  borrowed->vector.length = INT64_C(0);
  borrowed->vector.capacity = INT64_C(0);
}

static int generated_status(int64_t status, char *error,
                            size_t error_capacity,
                            const char *failure_detail) {
  if (status == (int64_t)FRAM_SERVER_OK) {
    return FRAM_SERVER_OK;
  }
  copy_error(error, error_capacity, failure_detail);
  return FRAM_SERVER_FATAL;
}

static int realtime_milliseconds(int64_t *milliseconds_out, char *error,
                                 size_t error_capacity) {
  struct timespec now;

  if (clock_gettime(CLOCK_REALTIME, &now) != 0 || now.tv_sec < (time_t)0 ||
      now.tv_nsec < 0 || now.tv_nsec >= 1000000000L ||
      (uintmax_t)now.tv_sec > (uintmax_t)(INT64_MAX / INT64_C(1000))) {
    copy_error(error, error_capacity,
               "cannot read a bounded realtime dispatch clock");
    return FRAM_SERVER_FATAL;
  }
  *milliseconds_out =
      (int64_t)now.tv_sec * INT64_C(1000) + (int64_t)(now.tv_nsec / 1000000L);
  return FRAM_SERVER_OK;
}

static int read_exact(int fd, uint8_t *destination, size_t length,
                      bool clean_eof_is_peer_closed,
                      int failure_status,
                      const char *truncated_detail, const char *read_detail,
                      char *error, size_t error_capacity) {
  size_t position = 0u;

  while (position < length) {
    ssize_t count = read(fd, destination + position, length - position);

    if (count > 0) {
      position += (size_t)count;
      continue;
    }
    if (count == 0) {
      if (position == 0u && clean_eof_is_peer_closed) {
        return FRAM_SERVER_PEER_CLOSED;
      }
      copy_error(error, error_capacity, truncated_detail);
      return failure_status;
    }
    if (errno == EINTR) {
      continue;
    }
    copy_error(error, error_capacity, read_detail);
    return failure_status;
  }
  return FRAM_SERVER_OK;
}

static int open_log(const char *path, int *fd_out, size_t *length_out,
                    char *error, size_t error_capacity) {
  struct stat status;
  int fd = open(path, O_RDWR | O_CLOEXEC);
  size_t length;

  if (fd < 0) {
    copy_error(error, error_capacity, "cannot open the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  if (fstat(fd, &status) != 0 || !S_ISREG(status.st_mode) ||
      status.st_size < 0 || (uintmax_t)status.st_size > (uintmax_t)SIZE_MAX ||
      (uintmax_t)status.st_size > (uintmax_t)INT64_MAX) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is not a readable regular file");
    (void)close(fd);
    return FRAM_SERVER_FATAL;
  }
  length = (size_t)status.st_size;
  *fd_out = fd;
  *length_out = length;
  return FRAM_SERVER_OK;
}

static int vector_length(const native_vec *vector, size_t minimum,
                         size_t maximum, size_t *length_out, char *error,
                         size_t error_capacity,
                         const char *invalid_detail) {
  int64_t length;

  if (vector == NULL) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  length = native_vec_length(vector);
  if (length < INT64_C(0) || (uint64_t)length > (uint64_t)SIZE_MAX ||
      (size_t)length < minimum || (size_t)length > maximum) {
    copy_error(error, error_capacity, invalid_detail);
    return FRAM_SERVER_FATAL;
  }
  *length_out = (size_t)length;
  return FRAM_SERVER_OK;
}

static int write_vector(int fd, const native_vec *vector, size_t minimum,
                        size_t maximum, bool peer_close_is_status,
                        int write_failure_status,
                        size_t *length_out, char *error,
                        size_t error_capacity, const char *invalid_detail,
                        const char *write_detail) {
  uint8_t chunk[FRAM_SERVER_IO_CHUNK_BYTES];
  size_t length;
  size_t offset = 0u;
  int status = vector_length(vector, minimum, maximum, &length, error,
                             error_capacity, invalid_detail);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  while (offset < length) {
    size_t count = length - offset;
    size_t index;
    size_t written = 0u;

    if (count > sizeof(chunk)) {
      count = sizeof(chunk);
    }
    for (index = 0u; index < count; index += 1u) {
      const int64_t *value = native_vec_at(
          vector, (int64_t)(offset + index), INT64_C(8));

      if (*value < INT64_C(0) || *value > INT64_C(255)) {
        copy_error(error, error_capacity, invalid_detail);
        return FRAM_SERVER_FATAL;
      }
      chunk[index] = (uint8_t)*value;
    }
    while (written < count) {
      ssize_t result = write(fd, chunk + written, count - written);

      if (result > 0) {
        written += (size_t)result;
        continue;
      }
      if (result < 0 && errno == EINTR) {
        continue;
      }
      if (peer_close_is_status && result < 0 &&
          (errno == EPIPE || errno == ECONNRESET)) {
        return FRAM_SERVER_PEER_CLOSED;
      }
      copy_error(error, error_capacity, write_detail);
      return write_failure_status;
    }
    offset += count;
  }
  if (length_out != NULL) {
    *length_out = length;
  }
  return FRAM_SERVER_OK;
}

static int append_log_vector(fram_server_store *store,
                             const native_vec *vector, bool sync_after_write,
                             char *error, size_t error_capacity) {
  size_t length;
  int status = vector_length(vector, 0u, SIZE_MAX, &length, error,
                             error_capacity,
                             "generated FRAMLOG append is not byte-valued");

  if (status != FRAM_SERVER_OK || length == 0u) {
    return status;
  }
  if (lseek(store->log_fd, (off_t)0, SEEK_END) < (off_t)0) {
    copy_error(error, error_capacity, "cannot seek the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  status = write_vector(store->log_fd, vector, 0u, SIZE_MAX, false,
                        FRAM_SERVER_FATAL, NULL, error, error_capacity,
                        "generated FRAMLOG append is not byte-valued",
                        "cannot append the canonical FRAMLOG");
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  if (sync_after_write && fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  return FRAM_SERVER_OK;
}

static int repair_log_tail(fram_server_store *store,
                           size_t original_length, int64_t valid_length,
                           char *error, size_t error_capacity) {
  off_t valid_offset;

  if (valid_length < INT64_C(0) ||
      (uint64_t)valid_length > (uint64_t)original_length) {
    copy_error(error, error_capacity,
               "generated FRAMLOG recovery returned an invalid prefix");
    return FRAM_SERVER_FATAL;
  }
  if ((size_t)valid_length == original_length) {
    return FRAM_SERVER_OK;
  }
  valid_offset = (off_t)valid_length;
  if ((int64_t)valid_offset != valid_length ||
      ftruncate(store->log_fd, valid_offset) != 0) {
    copy_error(error, error_capacity,
               "cannot repair the canonical FRAMLOG tail");
    return FRAM_SERVER_FATAL;
  }
  return FRAM_SERVER_OK;
}

static uint32_t frame_body_length(const uint8_t *header) {
  return (uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET] |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 1u]
          << 8u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 2u]
          << 16u) |
         ((uint32_t)header[FRAM_SERVER_FRAME_BODY_LENGTH_OFFSET + 3u]
          << 24u);
}

static int read_frame(int fd, uint8_t **frame_out, size_t *length_out,
                      char *error, size_t error_capacity) {
  uint8_t header[FRAM_SERVER_FRAME_HEADER_BYTES];
  uint8_t *frame;
  uint32_t body_length;
  size_t frame_length;
  int status = read_exact(
      fd, header, sizeof(header), true, FRAM_SERVER_CLIENT_ERROR,
      "generated request frame ended inside its header",
      "cannot read the generated request frame header", error,
      error_capacity);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  body_length = frame_body_length(header);
  if (body_length > FRAM_SERVER_FRAME_MAX_BODY_BYTES) {
    copy_error(error, error_capacity,
               "generated request frame exceeds the body limit");
    return FRAM_SERVER_CLIENT_ERROR;
  }
  frame_length = sizeof(header) + (size_t)body_length;
  frame = malloc(frame_length);
  if (frame == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request frame");
    return FRAM_SERVER_FATAL;
  }
  memcpy(frame, header, sizeof(header));
  status = read_exact(fd, frame + sizeof(header), (size_t)body_length, false,
                      FRAM_SERVER_CLIENT_ERROR,
                      "generated request frame ended inside its body",
                      "cannot read the generated request frame body", error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    free(frame);
    return status;
  }
  *frame_out = frame;
  *length_out = frame_length;
  return FRAM_SERVER_OK;
}

static int boot_generation_from_log(
    int log_fd, const char *canonical_log_path, const char *space_id,
    generated_store_generation **generation_out, size_t *log_length_out,
    char *error, size_t error_capacity) {
  struct stat file_status;
  generated_owner *owner = NULL;
  generated_store_generation *generation = NULL;
  uint8_t *log_bytes = NULL;
  borrowed_byte_vector borrowed;
  size_t log_length;
  fram_server_store_boot_arg_0 generated_log_path;
  fram_server_store_boot_arg_1 generated_space_id;
  fram_server_store_boot_return result;
  int status = FRAM_SERVER_FATAL;

  *generation_out = NULL;
  memset(&borrowed, 0, sizeof(borrowed));
  if (fstat(log_fd, &file_status) != 0 || !S_ISREG(file_status.st_mode) ||
      file_status.st_size < 0 ||
      (uintmax_t)file_status.st_size > (uintmax_t)SIZE_MAX ||
      (uintmax_t)file_status.st_size > (uintmax_t)INT64_MAX ||
      lseek(log_fd, (off_t)0, SEEK_SET) != (off_t)0) {
    copy_error(error, error_capacity,
               "cannot inspect the canonical FRAMLOG for generated boot");
    return FRAM_SERVER_FATAL;
  }
  log_length = (size_t)file_status.st_size;
  owner = owner_create(error, error_capacity);
  if (owner == NULL) {
    return FRAM_SERVER_FATAL;
  }
  if (log_length != 0u) {
    log_bytes = malloc(log_length);
  }
  if (log_length != 0u && log_bytes == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the canonical FRAMLOG input");
    goto cleanup;
  }
  status = read_exact(log_fd, log_bytes, log_length, false,
                      FRAM_SERVER_FATAL,
                      "canonical FRAMLOG ended while reading",
                      "cannot read the canonical FRAMLOG", error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    goto cleanup;
  }
  if (!borrowed_byte_vector_init(&borrowed, log_bytes, log_length, error,
                                 error_capacity)) {
    status = FRAM_SERVER_FATAL;
    goto cleanup;
  }
  free(log_bytes);
  log_bytes = NULL;
  generated_log_path = native_text_from_c(&owner->arena, canonical_log_path);
  generated_space_id =
      native_text_from_c(&owner->arena, space_id != NULL ? space_id : "");
  result = FRAM_SERVER_CALL_STORE_BOOT(
      &owner->arena, &owner->capability, generated_log_path,
      generated_space_id, &borrowed.vector);
  status = generated_status((int64_t)result.field_0, error, error_capacity,
                            "generated store boot failed");
  if (status == FRAM_SERVER_OK) {
    generation = generation_create(owner, NULL, result, error, error_capacity);
    if (generation == NULL) {
      status = FRAM_SERVER_FATAL;
    }
  }

cleanup:
  borrowed_byte_vector_destroy(&borrowed);
  free(log_bytes);
  owner_release(owner);
  if (status != FRAM_SERVER_OK) {
    if (generation != NULL) {
      generation_release(generation);
    }
    return FRAM_SERVER_FATAL;
  }
  *generation_out = generation;
  *log_length_out = log_length;
  return FRAM_SERVER_OK;
}

static bool store_needs_compaction(const fram_server_store *store) {
  const generated_store_generation *current = store->current;

  return current->chain_generations - store->compaction_base_generations >=
             FRAM_SERVER_COMPACT_GENERATIONS ||
         current->chain_reserved_bytes - store->compaction_base_bytes >=
             FRAM_SERVER_COMPACT_INCREMENT_BYTES;
}

static int compact_store(fram_server_store *store, char *error,
                         size_t error_capacity) {
  generated_store_generation *replacement = NULL;
  generated_store_generation *previous;
  size_t log_length;
  size_t append_length;
  int status = boot_generation_from_log(
      store->log_fd, store->canonical_log_path, store->space_id, &replacement,
      &log_length, error, error_capacity);

  if (status != FRAM_SERVER_OK) {
    return status;
  }
  status = vector_length(replacement->result.field_4, 0u, SIZE_MAX,
                         &append_length, error, error_capacity,
                         "generated compacted FRAMLOG append is invalid");
  if (status != FRAM_SERVER_OK || append_length != 0u ||
      replacement->result.field_3 < INT64_C(0) ||
      (uint64_t)replacement->result.field_3 != (uint64_t)log_length) {
    generation_release(replacement);
    copy_error(error, error_capacity,
               "generated compaction did not consume the canonical FRAMLOG");
    return FRAM_SERVER_FATAL;
  }
  previous = store->current;
  store->current = replacement;
  store->compaction_base_bytes = replacement->chain_reserved_bytes;
  store->compaction_base_generations = replacement->chain_generations;
  generation_release(previous);
  return FRAM_SERVER_OK;
}

uint32_t fram_server_generated_abi(void) {
  generated_owner *owner = owner_create(NULL, 0u);
  fram_server_generated_abi_return result;

  if (owner == NULL) {
    return UINT32_C(0);
  }
  result = FRAM_SERVER_CALL_GENERATED_ABI(&owner->arena,
                                              &owner->capability);
  owner_release(owner);
  if ((int64_t)result < INT64_C(0) ||
      (int64_t)result > (int64_t)UINT32_MAX) {
    return UINT32_C(0);
  }
  return (uint32_t)result;
}

int fram_server_store_boot(const char *canonical_log_path,
                               const char *space_id,
                               fram_server_store **store_out, char *error,
                               size_t error_capacity) {
  fram_server_store *store = NULL;
  generated_store_generation *generation = NULL;
  size_t log_length;
  int log_fd;
  size_t append_length;
  int status;

  clear_error(error, error_capacity);
  if (store_out == NULL || canonical_log_path == NULL) {
    copy_error(error, error_capacity,
               "generated store boot requires a log path and output owner");
    return FRAM_SERVER_FATAL;
  }
  *store_out = NULL;
  status = open_log(canonical_log_path, &log_fd, &log_length, error,
                    error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  store = malloc(sizeof(*store));
  if (store == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated store wrapper");
    (void)close(log_fd);
    return FRAM_SERVER_FATAL;
  }
  memset(store, 0, sizeof(*store));
  store->canonical_log_path =
      duplicate_string(canonical_log_path, error, error_capacity);
  store->space_id = duplicate_string(space_id != NULL ? space_id : "", error,
                                     error_capacity);
  if (store->canonical_log_path == NULL || store->space_id == NULL) {
    status = FRAM_SERVER_FATAL;
    goto boot_failed;
  }
  store->log_fd = log_fd;
  store->poisoned = false;
  status = boot_generation_from_log(
      log_fd, store->canonical_log_path, store->space_id, &generation,
      &log_length, error, error_capacity);
  if (status == FRAM_SERVER_OK) {
    store->current = generation;
    status = repair_log_tail(store, log_length,
                             (int64_t)generation->result.field_3, error,
                             error_capacity);
  }
  if (status == FRAM_SERVER_OK) {
    status = vector_length(generation->result.field_4, 0u, SIZE_MAX,
                           &append_length, error, error_capacity,
                           "generated boot append is not byte-valued");
  }
  if (status == FRAM_SERVER_OK && append_length != 0u) {
    status = append_log_vector(store, generation->result.field_4, false,
                               error, error_capacity);
  }
  if (status == FRAM_SERVER_OK && fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  if (status != FRAM_SERVER_OK) {
    goto boot_failed;
  }
  store->compaction_base_bytes = generation->chain_reserved_bytes;
  store->compaction_base_generations = generation->chain_generations;
  *store_out = store;
  return FRAM_SERVER_OK;

boot_failed:
  if (generation != NULL) {
    generation_release(generation);
  }
  free(store->space_id);
  free(store->canonical_log_path);
  free(store);
  (void)close(log_fd);
  return FRAM_SERVER_FATAL;
}

int fram_server_store_dispatch(fram_server_store *store,
                                   const fram_server_request *request,
                                   fram_server_response **response_out,
                                   char *error, size_t error_capacity) {
  fram_server_response *response;
  generated_store_generation *base_generation;
  generated_store_generation *next_generation = NULL;
  fram_server_store_dispatch_arg_2 now_milliseconds;
  int64_t clock_milliseconds;
  size_t append_length;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL || request == NULL || response_out == NULL) {
    copy_error(error, error_capacity,
               "generated dispatch requires owned input and output values");
    return FRAM_SERVER_FATAL;
  }
  *response_out = NULL;
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    return FRAM_SERVER_FATAL;
  }
  if (store_needs_compaction(store)) {
    status = compact_store(store, error, error_capacity);
    if (status != FRAM_SERVER_OK) {
      return status;
    }
  }
  status = realtime_milliseconds(&clock_milliseconds, error, error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  now_milliseconds =
      (fram_server_store_dispatch_arg_2)clock_milliseconds;
  response = malloc(sizeof(*response));
  if (response == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated response wrapper");
    return FRAM_SERVER_FATAL;
  }
  base_generation = store->current;
  owner_retain(request->owner);
  generation_retain(base_generation);
  response->scratch_owner = request->owner;
  response->base_generation = base_generation;
  response->result = FRAM_SERVER_CALL_STORE_DISPATCH(
      &request->owner->arena, &request->owner->capability,
      base_generation->result, request->result, now_milliseconds);
  status = generated_status((int64_t)response->result.field_0, error,
                            error_capacity,
                            "generated store dispatch failed");
  if (status == FRAM_SERVER_OK) {
    status = vector_length(response->result.field_3, 0u, SIZE_MAX,
                           &append_length, error, error_capacity,
                           "generated dispatch append is not byte-valued");
  }
  if (status == FRAM_SERVER_OK && append_length != 0u &&
      !response->result.field_5) {
    copy_error(error, error_capacity,
               "generated dispatch appended without changing state");
    status = FRAM_SERVER_FATAL;
  }
  if (status == FRAM_SERVER_OK && response->result.field_5) {
    next_generation = generation_create(
        request->owner, base_generation, response->result.field_4, error,
        error_capacity);
    if (next_generation == NULL) {
      status = FRAM_SERVER_FATAL;
    }
  }
  if (status == FRAM_SERVER_OK && append_length != 0u) {
    status = append_log_vector(store, response->result.field_3, true, error,
                               error_capacity);
    if (status != FRAM_SERVER_OK) {
      store->poisoned = true;
    }
  }
  if (status == FRAM_SERVER_OK && next_generation != NULL) {
    generated_store_generation *previous = store->current;

    store->current = next_generation;
    next_generation = NULL;
    generation_release(previous);
  }
  if (status != FRAM_SERVER_OK) {
    (void)FRAM_SERVER_CALL_CODEC_RELEASE_RESPONSE(
        &request->owner->arena, &request->owner->capability, response->result);
    if (next_generation != NULL) {
      generation_release(next_generation);
    }
    generation_release(response->base_generation);
    owner_release(response->scratch_owner);
    free(response);
    return FRAM_SERVER_FATAL;
  }
  *response_out = response;
  return FRAM_SERVER_OK;
}

int fram_server_store_shutdown(fram_server_store *store, char *error,
                                   size_t error_capacity) {
  fram_server_store_shutdown_return generated_result;
  int status;

  clear_error(error, error_capacity);
  if (store == NULL) {
    copy_error(error, error_capacity,
               "generated store shutdown requires an owned store");
    return FRAM_SERVER_FATAL;
  }
  generated_result = FRAM_SERVER_CALL_STORE_SHUTDOWN(
      &store->current->owner->arena, &store->current->owner->capability,
      store->current->result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated store shutdown failed");
  if (store->poisoned) {
    copy_error(error, error_capacity,
               "canonical FRAMLOG is poisoned after a durability failure");
    status = FRAM_SERVER_FATAL;
  }
  if (fsync(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot sync the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  if (close(store->log_fd) != 0) {
    copy_error(error, error_capacity, "cannot close the canonical FRAMLOG");
    status = FRAM_SERVER_FATAL;
  }
  generation_release(store->current);
  free(store->space_id);
  free(store->canonical_log_path);
  free(store);
  return status;
}

int fram_server_codec_read_request(int client_fd,
                                       fram_server_request **request_out,
                                       char *error, size_t error_capacity) {
  fram_server_request *request;
  generated_owner *owner;
  uint8_t *frame;
  size_t frame_length;
  borrowed_byte_vector borrowed;
  int status;

  clear_error(error, error_capacity);
  if (request_out == NULL) {
    copy_error(error, error_capacity,
               "generated request read requires an output owner");
    return FRAM_SERVER_FATAL;
  }
  *request_out = NULL;
  status = read_frame(client_fd, &frame, &frame_length, error,
                      error_capacity);
  if (status != FRAM_SERVER_OK) {
    return status;
  }
  owner = owner_create(error, error_capacity);
  if (owner == NULL) {
    free(frame);
    return FRAM_SERVER_FATAL;
  }
  request = malloc(sizeof(*request));
  if (request == NULL) {
    copy_error(error, error_capacity,
               "cannot allocate the generated request wrapper");
    free(frame);
    owner_release(owner);
    return FRAM_SERVER_FATAL;
  }
  request->owner = owner;
  if (!borrowed_byte_vector_init(&borrowed, frame, frame_length, error,
                                 error_capacity)) {
    free(frame);
    owner_release(owner);
    free(request);
    return FRAM_SERVER_FATAL;
  }
  free(frame);
  request->result = FRAM_SERVER_CALL_CODEC_READ_REQUEST(
      &owner->arena, &owner->capability, &borrowed.vector);
  borrowed_byte_vector_destroy(&borrowed);
  status = generated_status((int64_t)request->result.field_0, error,
                            error_capacity,
                            "generated request decode failed");
  if (status != FRAM_SERVER_OK) {
    (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
        &owner->arena, &owner->capability, request->result);
    owner_release(owner);
    free(request);
    return FRAM_SERVER_CLIENT_ERROR;
  }
  *request_out = request;
  return FRAM_SERVER_OK;
}

int fram_server_codec_write_response(
    int client_fd, const fram_server_response *response, char *error,
    size_t error_capacity) {
  generated_owner *owner;
  fram_server_codec_write_response_return generated_result;
  int status;

  clear_error(error, error_capacity);
  if (response == NULL) {
    copy_error(error, error_capacity,
               "generated response write requires an owned response");
    return FRAM_SERVER_FATAL;
  }
  owner = owner_create(error, error_capacity);
  if (owner == NULL) {
    return FRAM_SERVER_FATAL;
  }
  generated_result = FRAM_SERVER_CALL_CODEC_WRITE_RESPONSE(
      &owner->arena, &owner->capability, response->result);
  status = generated_status((int64_t)generated_result.field_0, error,
                            error_capacity,
                            "generated response encode failed");
  if (status == FRAM_SERVER_OK) {
    status = write_vector(
        client_fd, generated_result.field_1,
        FRAM_SERVER_FRAME_HEADER_BYTES,
        FRAM_SERVER_FRAME_MAX_BYTES, true,
        FRAM_SERVER_CLIENT_ERROR, NULL, error, error_capacity,
        "generated response frame has an invalid byte representation",
        "cannot write the generated response frame");
  }
  owner_release(owner);
  return status;
}

void fram_server_codec_release_request(fram_server_request *request) {
  if (request == NULL) {
    return;
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_REQUEST(
      &request->owner->arena, &request->owner->capability, request->result);
  owner_release(request->owner);
  free(request);
}

void fram_server_codec_release_response(
    fram_server_response *response) {
  if (response == NULL) {
    return;
  }
  (void)FRAM_SERVER_CALL_CODEC_RELEASE_RESPONSE(
      &response->scratch_owner->arena, &response->scratch_owner->capability,
      response->result);
  generation_release(response->base_generation);
  owner_release(response->scratch_owner);
  free(response);
}
