export type {
  IntegerInput,
  StringTerm,
  IntegerTerm,
  Float64Term,
  BooleanTerm,
  KeywordTerm,
  InstantTerm,
  TripleTerm,
  Term,
  TermInput,
  TransactionCoordinateTerm,
  OccurrenceCoordinateTerm,
  OccurrenceAction,
  Occurrence,
  QueryVariable,
  QueryTermInput,
  QueryHead,
  QueryRelationClause,
  QueryPredicateClause,
  QueryFunctionClause,
  QueryClause,
  QueryRule,
  QueryAggregate,
  QueryHaving,
  QueryAggregateFind,
  StructuredQueryRules,
  StructuredQueryStrata,
  StructuredQuery,
  TriplePattern,
  PageRequest,
  PageResponse,
  RequestOptions,
  PagedRequestOptions,
  SinceSelector,
  QueryOptions,
  WriteOptions,
  BatchAction,
  BatchPreflight,
  BatchPreflightOptions,
  BatchOptions,
  FramResponse,
  MutationActionResult,
  StatusResult,
  ValidationResult,
  FramInstant,
  LeaseGrant,
  LeaseCheck,
  FramClient,
  FramNativeCheckpointResult,
  FramTransportEntry,
  FramTransportRequest,
  FramTransport,
  FramTransportClientOptions,
} from '@tompassarelli/framrpc';

export {
  FRAMRPC_VERSION,
  FRAMRPC_MAX_BATCH_ACTIONS,
  FRAMRPC_MAX_FRAME_BYTES,
  FramProtocolError,
  FramTransportError,
  FramRpcError,
  stringTerm,
  integerTerm,
  float64Term,
  booleanTerm,
  keywordTerm,
  instantTerm,
  tripleTerm,
  validateTerm,
  term,
  float64Value,
  integerValue,
  listValues,
  recordFields,
  lowerQueryPlan,
  tripleQuery,
  framTransportCheckpoint,
  framRpcDeclaredFrameBytes,
} from '@tompassarelli/framrpc';

import type {
  FramClient,
  FramTransportClientOptions,
} from '@tompassarelli/framrpc';

/** Runtime-neutral FRAMRPC client over an injected exact-frame transport. */
export function framClient(options: FramTransportClientOptions): FramClient;
